// ui/src/components/chat/conversation-sidebar.tsx
// The plan rail — LEFT, on the shared Rail primitives (agent picker up top,
// this agent's plans below, plans shared with you at the end). Rows follow
// the Gentle dew session-list pattern (spec §10): status dot, 13px sans
// title, right-aligned mono meta/time; the active row carries the gold dot.
import { Plus } from 'lucide-react'
import { useHasPerm } from '@/lib/session'
import { AgentPicker } from '@/components/chat/agent-picker'
import { IconButton } from '@/components/ui/icon-button'
import { Rail, RailRow, RailSection } from '@/components/app/surface'
import { SkeletonRows } from '@/components/ui/skeleton'
import { relativeTime } from '@/lib/fleet'
import type { AgentModel } from '@/lib/agents'
import type { Conversation } from '@/lib/conversations'

/** §10 session row content: [status dot] [13px title] [mono owner] [mono time]. */
function SessionRowBody({ conv, active }: { conv: Conversation; active: boolean }) {
  // Semantic first (spec §1): failure orange, working green; the active row's
  // dot reads gold, idle rows stay dim ink.
  const dot = conv.failed
    ? 'var(--theme-danger)'
    : conv.working
      ? 'var(--theme-success)'
      : active
        ? 'var(--theme-accent)'
        : 'var(--theme-ink-dim)'
  return (
    <>
      <span
        aria-hidden
        className="h-[6px] w-[6px] shrink-0 rounded-full"
        style={{ backgroundColor: dot }}
      />
      <span className="min-w-0 flex-1 truncate font-sans text-[13px]">{conv.title || 'Untitled'}</span>
      {conv.ownerLabel && (
        <span className="max-w-16 shrink-0 truncate font-mono text-[10px] tracking-[0.05em] text-muted">
          {conv.ownerLabel}
        </span>
      )}
      <span className="shrink-0 font-mono text-[10px] tracking-[0.05em] text-ink-dim">
        {relativeTime(conv.updatedAt)}
      </span>
    </>
  )
}

export function ConversationSidebar({
  agents,
  conversations,
  selectedAgent,
  selectedConversationId,
  agentsLoading,
  conversationsLoading,
  onSelectAgent,
  onSelectConversation,
  onNewChat,
}: {
  agents: AgentModel[]
  conversations: Conversation[]
  selectedAgent: string | null
  selectedConversationId: string | null
  agentsLoading?: boolean
  conversationsLoading?: boolean
  onSelectAgent: (agentModel: string) => void
  onSelectConversation: (conv: Conversation) => void
  onNewChat: () => void
}) {
  const agentConvs = conversations.filter((c) => c.agentModel === selectedAgent)
  const sharedElsewhere = conversations.filter((c) => c.role === 'collaborator' && c.agentModel !== selectedAgent)

  return (
    <Rail
      title="Plan"
      actions={
        useHasPerm('plans.create') ? (
          <IconButton size="sm" title="New plan: think it through, then draft tickets" onClick={onNewChat} disabled={!selectedAgent}><Plus size={15} /></IconButton>
        ) : null
      }
    >
      <div className="mb-3">
        <AgentPicker agents={agents} value={selectedAgent} onChange={onSelectAgent} loading={agentsLoading} fullWidth />
      </div>

      {conversationsLoading ? (
        <SkeletonRows rows={5} className="px-2 pt-1.5" />
      ) : agentConvs.length === 0 ? (
        <div className="px-2 py-6 text-center text-xs text-muted">No plans yet with this agent.</div>
      ) : (
        <ul className="space-y-0.5">
          {agentConvs.map((c) => (
            <RailRow key={c.id} active={c.id === selectedConversationId} onClick={() => onSelectConversation(c)}>
              <SessionRowBody conv={c} active={c.id === selectedConversationId} />
            </RailRow>
          ))}
        </ul>
      )}

      {/* Plans shared WITH you ride other agents — always visible. */}
      {sharedElsewhere.length > 0 && (
        <div className="mt-4">
          <RailSection label="Shared with you">
            {sharedElsewhere.map((c) => (
              <RailRow key={c.id} active={c.id === selectedConversationId} onClick={() => onSelectConversation(c)}>
                <SessionRowBody conv={c} active={c.id === selectedConversationId} />
              </RailRow>
            ))}
          </RailSection>
        </div>
      )}
    </Rail>
  )
}

// ui/src/components/chat/ConversationSidebar.svelte
<script lang="ts">
  // The plan rail — LEFT, on the shared Rail primitives (agent picker up top,
  // this agent's plans below, plans shared with you at the end). Rows follow
  // the Mercury session-list pattern (spec §10): status dot, 13px sans
  // title, right-aligned mono meta/time; the active row carries the gold dot.
  import { Plus } from '@lucide/svelte'
  import { useHasPerm } from '@/lib/session'
  import AgentPicker from '@/components/chat/AgentPicker.svelte'
  import SessionRowBody from '@/components/chat/SessionRowBody.svelte'
  import IconButton from '@/components/ui/IconButton.svelte'
  import Rail from '@/components/app/Rail.svelte'
  import RailRow from '@/components/app/RailRow.svelte'
  import RailSection from '@/components/app/RailSection.svelte'
  import SkeletonRows from '@/components/ui/SkeletonRows.svelte'
  import QueryError from '@/components/ui/QueryError.svelte'
  import type { AgentModel } from '@/lib/agents'
  import type { Conversation } from '@/lib/conversations.svelte'
  import type { SidebarFailure } from './conversation-sidebar'

  let {
    agents,
    conversations,
    selectedAgent,
    selectedConversationId,
    agentsLoading,
    conversationsLoading,
    agentsFailure = null,
    conversationsFailure = null,
    onSelectAgent,
    onSelectConversation,
    onNewChat,
  }: {
    agents: AgentModel[]
    conversations: Conversation[]
    selectedAgent: string | null
    selectedConversationId: string | null
    agentsLoading?: boolean
    conversationsLoading?: boolean
    agentsFailure?: SidebarFailure
    conversationsFailure?: SidebarFailure
    onSelectAgent: (agentModel: string) => void
    onSelectConversation: (conv: Conversation) => void
    onNewChat: () => void
  } = $props()

  const canCreatePlans = useHasPerm('plans.create')
  const agentConvs = $derived(conversations.filter((c) => c.agentModel === selectedAgent))
  const sharedElsewhere = $derived(
    conversations.filter((c) => c.role === 'collaborator' && c.agentModel !== selectedAgent),
  )
</script>

<Rail title="Plan">
  {#snippet actions()}
    {#if canCreatePlans.current}
      <IconButton size="sm" title="New plan: think it through, then draft tickets" onclick={onNewChat} disabled={!selectedAgent}><Plus size={15} /></IconButton>
    {/if}
  {/snippet}

  <div class="mb-3">
    <AgentPicker {agents} value={selectedAgent} onChange={onSelectAgent} loading={agentsLoading} fullWidth />
    <!-- An empty picker is indistinguishable from a fleet you don't have. -->
    {#if agentsFailure}
      <QueryError
        variant="inline"
        class="mt-1.5 px-2"
        error={agentsFailure.error}
        title="Could not load your agents"
        onRetry={agentsFailure.retry}
      />
    {/if}
  </div>

  {#if conversationsLoading}
    <SkeletonRows rows={5} class="px-2 pt-1.5" />
  {:else if conversationsFailure}
    <QueryError
      variant="compact"
      error={conversationsFailure.error}
      title="Could not load your plans"
      onRetry={conversationsFailure.retry}
    />
  {:else if agentConvs.length === 0}
    <div class="px-2 py-6 text-center text-xs text-muted">No plans yet with this agent.</div>
  {:else}
    <ul class="space-y-0.5">
      {#each agentConvs as c (c.id)}
        <RailRow active={c.id === selectedConversationId} onClick={() => onSelectConversation(c)}>
          <SessionRowBody conv={c} active={c.id === selectedConversationId} />
        </RailRow>
      {/each}
    </ul>
  {/if}

  <!-- Plans shared WITH you ride other agents — always visible. -->
  {#if sharedElsewhere.length > 0}
    <div class="mt-4">
      <RailSection label="Shared with you">
        {#each sharedElsewhere as c (c.id)}
          <RailRow active={c.id === selectedConversationId} onClick={() => onSelectConversation(c)}>
            <SessionRowBody conv={c} active={c.id === selectedConversationId} />
          </RailRow>
        {/each}
      </RailSection>
    </div>
  {/if}
</Rail>
