// ui/src/components/chat/guard-caveat.tsx
// The confab guard's caveat on a flagged agent reply (annotate/strict modes).
// Renders from message metadata — the findings are never part of the reply
// text, so they can't leak back into any transcript.

export interface GuardFinding {
  check: string
  severity: 'low' | 'medium' | 'high'
  confidence: number
  message: string
  snippet: string
}

export function GuardCaveat({ findings }: { findings?: GuardFinding[] | null }) {
  if (!findings?.length) return null
  return (
    // Attention panel (spec §8): gold hairline + mono uppercase label; body
    // stays readable sans on the readout tone.
    <div className="mt-2 space-y-1 rounded-md border px-2.5 py-2 text-xs" style={{ borderColor: 'var(--theme-warning)' }}>
      <div className="font-mono text-[10px] uppercase tracking-[0.08em]" style={{ color: 'var(--theme-warning)' }}>
        Unverified · confab guard flagged this reply
      </div>
      {findings.map((f, i) => (
        <div key={`${f.check}-${i}`} className="font-sans text-fg">
          <span className="font-mono text-[10px] uppercase tracking-[0.05em]" style={{ color: 'var(--theme-warning)' }}>
            {f.check.replace(/_/g, ' ')}
          </span>
          {' · '}
          {f.message}
          {f.snippet ? <span className="text-muted"> ({f.snippet})</span> : null}
        </div>
      ))}
    </div>
  )
}

// ui/src/components/chat/GuardCaveat.svelte
<script lang="ts">
  import type { GuardFinding } from './guard-caveat'

  // The confab guard's caveat on a flagged agent reply (annotate/strict modes).
  // Renders from message metadata — the findings are never part of the reply
  // text, so they can't leak back into any transcript.
  let { findings }: { findings?: GuardFinding[] | null } = $props()
</script>

{#if findings?.length}
  <!-- Attention panel (spec §8): gold hairline + mono uppercase label; body
       stays readable sans on the readout tone. -->
  <div class="mt-2 space-y-1 rounded-md border px-2.5 py-2 text-xs" style="border-color: var(--theme-warning)">
    <div class="font-mono text-[10px] uppercase tracking-[0.08em]" style="color: var(--theme-warning)">
      Unverified · confab guard flagged this reply
    </div>
    {#each findings as f, i (`${f.check}-${i}`)}
      <div class="font-sans text-fg">
        <span class="font-mono text-[10px] uppercase tracking-[0.05em]" style="color: var(--theme-warning)">
          {f.check.replace(/_/g, ' ')}
        </span>
        {' · '}
        {f.message}
        {#if f.snippet}<span class="text-muted"> ({f.snippet})</span>{/if}
      </div>
    {/each}
  </div>
{/if}
