// ui/src/components/fleet/federate-modal.tsx
import { useState } from 'react'
import { useQueryClient } from '@tanstack/react-query'
import { GeneratingBars } from '@/components/ui/generating'
import { Modal } from '@/components/ui/modal'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { submitOnEnter } from '@/components/ui/control'
import { Steps } from '@/components/ui/steps'
import { reconcileFleet } from '@/lib/fleet-defs'
import { cn } from '@/lib/cn'

interface FederateResult {
  agents: Array<{ slug: string; model: string; status: 'federated' | 'exists' }>
  errors: string[]
}

const STEPS = ['Source', 'Federate', 'Start'] as const

// Bring outside agents in — as natives. Reads a Hermes-format directory and
// recreates each agent inside Talaria: our chassis, our orchestration, fresh
// key and state volume, skills carried over. The source dir is not referenced
// again afterwards.
export function FederateModal({ onClose }: { onClose: () => void }) {
  const qc = useQueryClient()
  const [step, setStep] = useState(0)
  const [dir, setDir] = useState('')
  const [busy, setBusy] = useState(false)
  const [result, setResult] = useState<FederateResult | null>(null)
  const [started, setStarted] = useState<string | null>(null)
  const [err, setErr] = useState<string | null>(null)

  const federate = async () => {
    setBusy(true)
    setErr(null)
    try {
      const r = await fetch('/api/fleet/federate', {
        method: 'POST',
        credentials: 'same-origin',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ dir: dir.trim() }),
      })
      const j = (await r.json().catch(() => null)) as { result?: FederateResult; error?: string } | null
      if (!j?.result) return setErr(j?.error ?? 'federation failed')
      setResult(j.result)
      await qc.invalidateQueries({ queryKey: ['fleet-defs'] })
      setStep(1)
    } finally {
      setBusy(false)
    }
  }

  const startAll = async () => {
    setBusy(true)
    try {
      const r = await reconcileFleet()
      setStarted(r.error ?? `Started ${r.started?.length ?? 0} · already running ${r.alreadyRunning?.length ?? 0}`)
      await qc.invalidateQueries({ queryKey: ['fleet-containers'] })
      setStep(2)
    } finally {
      setBusy(false)
    }
  }

  const fresh = result?.agents.filter((a) => a.status === 'federated') ?? []

  const footer =
    step === 0 ? (
      <div className="flex justify-end gap-2">
        <Button variant="ghost" size="sm" onClick={onClose}>
          Cancel
        </Button>
        <Button size="sm" onClick={() => void federate()} disabled={busy || !dir.trim()}>
          {busy && <GeneratingBars bars={3} variant="weave" step={0.15} />}
          {busy ? 'Federating' : 'Federate'}
        </Button>
      </div>
    ) : step === 1 ? (
      <div className="flex justify-end gap-2">
        <Button variant="ghost" size="sm" onClick={onClose}>
          Close
        </Button>
        <Button size="sm" onClick={() => void startAll()} disabled={busy || fresh.length === 0}>
          {busy ? 'Starting' : `Start ${fresh.length} agent${fresh.length === 1 ? '' : 's'}`}
        </Button>
      </div>
    ) : (
      <div className="flex justify-end">
        <Button size="sm" onClick={onClose}>
          Done
        </Button>
      </div>
    )

  return (
    <Modal open onClose={onClose} title="Federate outside agents" width="max-w-lg" footer={footer}>
      <div className="space-y-5">
        <Steps steps={STEPS} current={step} />

        {step === 0 && (
          <div className="space-y-4">
            <p className="text-sm leading-relaxed text-muted">
              Point at a Hermes-format directory on the server (<code className="text-fg">agents.yaml</code> roster,
              each agent's <code className="text-fg">SOUL.md</code> + <code className="text-fg">config.yaml</code>).
              Each agent is recreated <em>natively</em>: Talaria's chassis and orchestration, a fresh key and state
              volume, models mapped into the registry, skills carried over. The source directory is never referenced
              again. Agents whose handle already exists are skipped.
            </p>
            <div>
              <label className="mb-1.5 block font-mono text-[10px] uppercase tracking-[0.08em] text-ink-dim">Directory on server</label>
              <Input value={dir} onChange={(e) => setDir(e.target.value)} onKeyDown={submitOnEnter(() => !busy && dir.trim() && void federate())} placeholder="/path/to/stack" autoFocus />
            </div>
            {err && <p className="text-xs text-danger">{err}</p>}
          </div>
        )}

        {step === 1 && result && (
          <div className="space-y-3">
            <div className="text-sm text-fg">
              {fresh.length} federated · {result.agents.length - fresh.length} already here
            </div>
            {result.agents.length > 0 && (
              <ul className="max-h-56 divide-y divide-line overflow-y-auto rounded-lg border border-line">
                {result.agents.map((a) => (
                  <li key={a.slug} className="flex items-center gap-2 px-3.5 py-2 text-sm">
                    <span className="font-mono text-xs text-fg">{a.slug}</span>
                    <span className={cn('ml-auto font-mono text-[10px] uppercase tracking-[0.05em]', a.status === 'federated' ? 'text-accent' : 'text-muted')}>
                      {a.status === 'federated' ? 'federated' : 'already exists'}
                    </span>
                  </li>
                ))}
              </ul>
            )}
            {result.errors.map((e) => (
              <p key={e} className="text-xs text-danger">
                {e}
              </p>
            ))}
          </div>
        )}

        {step === 2 && <p className="text-sm text-fg">{started}</p>}
      </div>
    </Modal>
  )
}

// ui/src/components/fleet/FederateModal.svelte
<script lang="ts">
  import { useQueryClient } from '@tanstack/svelte-query'
  import GeneratingBars from '@/components/ui/GeneratingBars.svelte'
  import Modal from '@/components/ui/Modal.svelte'
  import Button from '@/components/ui/Button.svelte'
  import Input from '@/components/ui/Input.svelte'
  import { submitOnEnter } from '@/components/ui/control'
  import Steps from '@/components/ui/Steps.svelte'
  import { reconcileFleet } from '@/lib/fleet-defs'
  import { cn } from '@/lib/cn'

  interface FederateResult {
    agents: Array<{ slug: string; model: string; status: 'federated' | 'exists' }>
    errors: string[]
  }

  const STEPS = ['Source', 'Federate', 'Start'] as const

  // Bring outside agents in — as natives. Reads a Hermes-format directory and
  // recreates each agent inside Talaria: our chassis, our orchestration, fresh
  // key and state volume, skills carried over. The source dir is not referenced
  // again afterwards.
  let { onClose }: { onClose: () => void } = $props()

  const qc = useQueryClient()
  let step = $state(0)
  let dir = $state('')
  let busy = $state(false)
  let result = $state<FederateResult | null>(null)
  let started = $state<string | null>(null)
  let err = $state<string | null>(null)

  const federate = async () => {
    busy = true
    err = null
    try {
      const r = await fetch('/api/fleet/federate', {
        method: 'POST',
        credentials: 'same-origin',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ dir: dir.trim() }),
      })
      const j = (await r.json().catch(() => null)) as { result?: FederateResult; error?: string } | null
      if (!j?.result) {
        err = j?.error ?? 'federation failed'
        return
      }
      result = j.result
      await qc.invalidateQueries({ queryKey: ['fleet-defs'] })
      step = 1
    } finally {
      busy = false
    }
  }

  const startAll = async () => {
    busy = true
    try {
      const r = await reconcileFleet()
      started = r.error ?? `Started ${r.started?.length ?? 0} · already running ${r.alreadyRunning?.length ?? 0}`
      await qc.invalidateQueries({ queryKey: ['fleet-containers'] })
      step = 2
    } finally {
      busy = false
    }
  }

  const fresh = $derived(result?.agents.filter((a) => a.status === 'federated') ?? [])
</script>

<Modal open onClose={onClose} title="Federate outside agents" width="max-w-lg">
  <div class="space-y-5">
    <Steps steps={STEPS} current={step} />

    {#if step === 0}
      <div class="space-y-4">
        <p class="text-sm leading-relaxed text-muted">
          Point at a Hermes-format directory on the server (<code class="text-fg">agents.yaml</code> roster,
          each agent's <code class="text-fg">SOUL.md</code> + <code class="text-fg">config.yaml</code>).
          Each agent is recreated <em>natively</em>: Talaria's chassis and orchestration, a fresh key and state
          volume, models mapped into the registry, skills carried over. The source directory is never referenced
          again. Agents whose handle already exists are skipped.
        </p>
        <div>
          <label class="mb-1.5 block font-mono text-[10px] uppercase tracking-[0.08em] text-ink-dim">Directory on server</label>
          <Input
            bind:value={dir}
            onkeydown={submitOnEnter(() => {
              if (!busy && dir.trim()) void federate()
            })}
            placeholder="/path/to/stack"
            autofocus
          />
        </div>
        {#if err}<p class="text-xs text-danger">{err}</p>{/if}
      </div>
    {/if}

    {#if step === 1 && result}
      <div class="space-y-3">
        <div class="text-sm text-fg">
          {fresh.length} federated · {result.agents.length - fresh.length} already here
        </div>
        {#if result.agents.length > 0}
          <ul class="max-h-56 divide-y divide-line overflow-y-auto rounded-lg border border-line">
            {#each result.agents as a (a.slug)}
              <li class="flex items-center gap-2 px-3.5 py-2 text-sm">
                <span class="font-mono text-xs text-fg">{a.slug}</span>
                <span class={cn('ml-auto font-mono text-[10px] uppercase tracking-[0.05em]', a.status === 'federated' ? 'text-accent' : 'text-muted')}>
                  {a.status === 'federated' ? 'federated' : 'already exists'}
                </span>
              </li>
            {/each}
          </ul>
        {/if}
        {#each result.errors as e (e)}
          <p class="text-xs text-danger">
            {e}
          </p>
        {/each}
      </div>
    {/if}

    {#if step === 2}<p class="text-sm text-fg">{started}</p>{/if}
  </div>

  {#snippet footer()}
    {#if step === 0}
      <div class="flex justify-end gap-2">
        <Button variant="ghost" size="sm" onclick={onClose}>
          Cancel
        </Button>
        <Button size="sm" onclick={() => void federate()} disabled={busy || !dir.trim()}>
          {#if busy}<GeneratingBars bars={3} variant="weave" step={0.15} />{/if}
          {busy ? 'Federating' : 'Federate'}
        </Button>
      </div>
    {:else if step === 1}
      <div class="flex justify-end gap-2">
        <Button variant="ghost" size="sm" onclick={onClose}>
          Close
        </Button>
        <Button size="sm" onclick={() => void startAll()} disabled={busy || fresh.length === 0}>
          {busy ? 'Starting' : `Start ${fresh.length} agent${fresh.length === 1 ? '' : 's'}`}
        </Button>
      </div>
    {:else}
      <div class="flex justify-end">
        <Button size="sm" onclick={onClose}>
          Done
        </Button>
      </div>
    {/if}
  {/snippet}
</Modal>
