// ui/src/routes/_app/admin.tsx
import { createFileRoute } from '@tanstack/react-router'
import { useEffect, useState } from 'react'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { Avatar } from '@/components/ui/avatar'
import { Combobox } from '@/components/ui/combobox'
import { Button, buttonClasses } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { EmptyState } from '@/components/ui/empty-state'
import { Panel } from '@/components/ui/panel'
import { Select } from '@/components/ui/select'
import { useAgents } from '@/lib/agents'
import { useSession } from '@/lib/session'
import { relativeTime } from '@/lib/fleet'
import { GATEABLE_VIEWS } from '@/lib/nav'
import { RetrievalPanel } from '@/components/admin/retrieval-panel'

export const Route = createFileRoute('/_app/admin')({
  component: AdminPage,
})

interface AdminUser {
  id: string
  email: string | null
  name: string | null
  role: 'admin' | 'member'
  lastSeenAt: string
  createdAt: string
  agentModels: string[]
  canMintKeys: boolean
  deniedViews: string[]
  pinnedAdmin: boolean
}

function useAdminUsers() {
  return useQuery({
    queryKey: ['admin-users'],
    queryFn: async (): Promise<AdminUser[] | null> => {
      const r = await fetch('/api/admin/users', { credentials: 'same-origin' })
      if (!r.ok) return null
      return ((await r.json()) as { users: AdminUser[] }).users
    },
  })
}

// The admin console: people, their roles, and which agents each may use.
function AdminPage() {
  const qc = useQueryClient()
  const { data: me } = useSession()
  const { data: users } = useAdminUsers()
  const { data: fleet } = useAgents()
  const agentOptions = (fleet?.agents ?? []).map((a) => ({ value: a.id, label: a.label, sub: a.role }))
  const [error, setError] = useState<string | null>(null)

  const update = async (userId: string, patch: { role?: 'admin' | 'member'; agentModels?: string[]; canMintKeys?: boolean; deniedViews?: string[] }) => {
    setError(null)
    const r = await fetch('/api/admin/users', {
      method: 'PUT',
      credentials: 'same-origin',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({ userId, ...patch }),
    })
    if (!r.ok) setError(((await r.json().catch(() => ({}))) as { error?: string }).error ?? 'update failed')
    await qc.invalidateQueries({ queryKey: ['admin-users'] })
  }

  if (me && me.role !== 'admin') {
    return <EmptyState icon="⛨" title="Admins only" hint="Ask an admin if you need access here." />
  }

  return (
    <div className="h-full overflow-y-auto p-8">
      <div className="mx-auto max-w-4xl space-y-8">
        <h1 className="mercury-text text-2xl font-semibold">Admin</h1>

        <SettingsPanel />

        <OrgGooglePanel />

        <RetrievalPanel />

        <Panel>
          <div className="mb-2 text-sm font-semibold text-fg">People</div>
          <p className="mb-4 text-xs text-muted">
            Roles, per-person agent access, and which views each member can reach. Empty = all (open by
            default); pick any to restrict. Admins always have full access.
          </p>
          {error && (
            <div className="mb-2 text-xs" style={{ color: 'var(--theme-danger)' }}>
              {error}
            </div>
          )}
          <ul className="divide-y divide-line-subtle">
            {(users ?? []).map((u) => {
              // Views shown as an ALLOW list (all selected by default); denying =
              // stored as gateable-minus-allowed.
              const allowedViews = GATEABLE_VIEWS.filter((v) => !u.deniedViews.includes(v.to)).map((v) => v.to)
              return (
                <li key={u.id} className="space-y-2 py-3">
                  <div className="flex items-center gap-3">
                    <Avatar name={u.name ?? u.email} className="h-7 w-7" />
                    <span className="min-w-0 flex-1">
                      <span className="block truncate text-sm text-fg">{u.name ?? u.email ?? u.id}</span>
                      <span className="block truncate text-xs text-muted">
                        {u.name && u.email ? u.email : `seen ${relativeTime(u.lastSeenAt)}`}
                      </span>
                    </span>
                    <Select
                      value={u.role}
                      size="sm"
                      disabled={u.pinnedAdmin || u.id === me?.id}
                      title={u.pinnedAdmin ? 'Pinned admin via AUTH_ADMIN_EMAILS' : u.id === me?.id ? 'You cannot demote yourself' : undefined}
                      onChange={(e) => void update(u.id, { role: e.target.value as 'admin' | 'member' })}
                      className="w-28 shrink-0"
                    >
                      <option value="member">Member</option>
                      <option value="admin">Admin</option>
                    </Select>
                    <label
                      className="flex shrink-0 items-center gap-1.5 text-xs text-muted"
                      title="May create API keys for the Talaria LLM gateway (Settings → API keys)"
                    >
                      <input
                        type="checkbox"
                        checked={u.role === 'admin' || u.canMintKeys}
                        disabled={u.role === 'admin'}
                        onChange={(e) => void update(u.id, { canMintKeys: e.target.checked })}
                        className="accent-[var(--theme-accent)]"
                      />
                      keys
                    </label>
                    <span className="w-16 shrink-0 text-right text-xs text-muted">{relativeTime(u.lastSeenAt)}</span>
                  </div>
                  {u.role !== 'admin' && (
                    <div className="flex items-center gap-2 pl-10">
                      <Combobox
                        options={agentOptions}
                        selected={u.agentModels}
                        onChange={(models) => void update(u.id, { agentModels: models })}
                        multiple
                        size="sm"
                        placeholder="All agents"
                        className="min-w-0 flex-1"
                      />
                      <Combobox
                        options={GATEABLE_VIEWS.map((v) => ({ value: v.to, label: v.label }))}
                        selected={allowedViews}
                        onChange={(views) =>
                          void update(u.id, { deniedViews: GATEABLE_VIEWS.filter((v) => !views.includes(v.to)).map((v) => v.to) })
                        }
                        multiple
                        size="sm"
                        placeholder="All views"
                        className="min-w-0 flex-1"
                      />
                    </div>
                  )}
                </li>
              )
            })}
          </ul>
        </Panel>
      </div>
    </div>
  )
}

// App-wide settings (grows over time). Audit retention is the first.
function SettingsPanel() {
  const qc = useQueryClient()
  const { data } = useQuery({
    queryKey: ['admin-settings'],
    queryFn: async (): Promise<{ auditRetentionDays: number }> => {
      const r = await fetch('/api/admin/settings')
      if (!r.ok) throw new Error('failed')
      return r.json()
    },
  })
  const [days, setDays] = useState('')
  const value = days !== '' ? days : String(data?.auditRetentionDays ?? '')
  const save = async () => {
    const n = Number(value)
    if (!Number.isFinite(n)) return
    await fetch('/api/admin/settings', {
      method: 'PUT',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({ auditRetentionDays: n }),
    })
    setDays('')
    await qc.invalidateQueries({ queryKey: ['admin-settings'] })
  }
  return (
    <Panel>
      <div className="mb-2 text-sm font-semibold text-fg">Settings</div>
      <div className="flex items-center gap-3">
        <div className="min-w-0 flex-1">
          <div className="text-sm text-fg">Audit retention</div>
          <div className="text-xs text-muted">How many days to keep the audit log. 0 = keep forever.</div>
        </div>
        <Input
          size="sm"
          type="number"
          value={value}
          onChange={(e) => setDays(e.target.value)}
          className="w-24 shrink-0"
        />
        <span className="shrink-0 text-xs text-muted">days</span>
        <Button size="sm" className="shrink-0" onClick={() => void save()} disabled={days === '' || Number(days) === data?.auditRetentionDays}>
          Save
        </Button>
      </div>
    </Panel>
  )
}

interface OrgGoogle {
  available: boolean
  connected: boolean
  email: string | null
  connectedAt: string | null
  targets: { driveFolderId: string | null; calendarId: string | null; sendAs: string | null }
}

// The shared org Google account general fleet agents act as for Drive/Docs.
function OrgGooglePanel() {
  const qc = useQueryClient()
  const { data } = useQuery({
    queryKey: ['org-google'],
    queryFn: async (): Promise<OrgGoogle> => {
      const r = await fetch('/api/integrations/google/org')
      if (!r.ok) throw new Error('failed')
      return r.json()
    },
  })
  const [flash, setFlash] = useState<string | null>(null)
  useEffect(() => {
    const p = new URLSearchParams(window.location.search).get('googleOrg')
    if (!p) return
    setFlash(p)
    window.history.replaceState({}, '', window.location.pathname)
    if (p === 'connected') void qc.invalidateQueries({ queryKey: ['org-google'] })
    const t = setTimeout(() => setFlash(null), 4000)
    return () => clearTimeout(t)
  }, [qc])

  const disconnect = async () => {
    if (!confirm('Disconnect the org Google account? General agents lose Drive/Docs access.')) return
    await fetch('/api/integrations/google/org', { method: 'DELETE' })
    await qc.invalidateQueries({ queryKey: ['org-google'] })
  }

  const msg: Record<string, string> = {
    connected: 'Org Google account connected.',
    denied: 'Connection cancelled.',
    bad_state: 'Connection expired — try again.',
    exchange_failed: 'Google rejected the connection — try again.',
    forbidden: 'Admins only.',
    disabled: 'Google integration is not configured.',
  }

  return (
    <Panel>
      <div className="mb-2 text-sm font-semibold text-fg">Organization Google account</div>
      <p className="mb-4 text-xs text-muted">
        A single shared Google account the fleet builds in. <strong>General agents</strong> (no personal owner)
        create Docs, Sheets, and Drive files here; a user's <strong>personal assistant</strong> instead acts as
        that user’s own connected Google.
      </p>
      {data && !data.available ? (
        <div className="text-xs text-muted">Google integration isn’t configured on this server.</div>
      ) : (
        <div className="flex items-center gap-3 rounded-xl border border-line-subtle p-4">
          <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg border border-line-subtle text-lg">🏢</div>
          <div className="min-w-0 flex-1">
            <div className="text-sm font-medium text-fg">Shared Drive & Docs</div>
            <div className="truncate text-xs text-muted">
              {data?.connected ? `Connected${data.email ? ` as ${data.email}` : ''}` : 'Not connected'}
            </div>
          </div>
          {data?.connected ? (
            <Button variant="ghost" size="sm" onClick={() => void disconnect()}>Disconnect</Button>
          ) : (
            <a href="/api/integrations/google/org/connect" className={buttonClasses({ size: 'sm' })}>Connect</a>
          )}
        </div>
      )}
      {data?.connected && <OrgGoogleTargets targets={data.targets} />}
      {flash && (
        <div className="mt-3 text-xs" style={{ color: flash === 'connected' ? 'var(--theme-success)' : 'var(--theme-danger)' }}>
          {msg[flash] ?? flash}
        </div>
      )}
    </Panel>
  )
}

// Where the org account's agents build: a Shared Drive so files are team-owned,
// a specific calendar, and an optional send-as alias for outgoing mail.
function OrgGoogleTargets({ targets }: { targets: OrgGoogle['targets'] }) {
  const qc = useQueryClient()
  const [drive, setDrive] = useState(targets.driveFolderId ?? '')
  const [cal, setCal] = useState(targets.calendarId ?? '')
  const [sendAs, setSendAs] = useState(targets.sendAs ?? '')
  const [saved, setSaved] = useState(false)
  const dirty = drive !== (targets.driveFolderId ?? '') || cal !== (targets.calendarId ?? '') || sendAs !== (targets.sendAs ?? '')

  const save = async () => {
    const r = await fetch('/api/integrations/google/org', {
      method: 'PUT',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({ driveFolderId: drive, calendarId: cal, sendAs }),
    })
    if (r.ok) {
      await qc.invalidateQueries({ queryKey: ['org-google'] })
      setSaved(true)
      setTimeout(() => setSaved(false), 1500)
    }
  }

  return (
    <div className="mt-4 space-y-3 rounded-xl border border-line-subtle p-4">
      <div className="text-xs font-medium text-fg">Where agents build</div>
      <div>
        <label className="mb-1 block text-[11px] uppercase tracking-wide text-muted">Shared Drive / folder ID</label>
        <Input size="sm" value={drive} onChange={(e) => setDrive(e.target.value)} placeholder="0Ae1a…  (Shared Drive or folder ID)" />
        <div className="mt-1 text-[11px] text-muted">Files agents create land here (team-owned). Blank = the account’s My Drive. The org account must be a member of the Shared Drive.</div>
      </div>
      <div>
        <label className="mb-1 block text-[11px] uppercase tracking-wide text-muted">Calendar ID</label>
        <Input size="sm" value={cal} onChange={(e) => setCal(e.target.value)} placeholder="team@group.calendar.google.com" />
        <div className="mt-1 text-[11px] text-muted">Org events land here. Blank = the account’s primary calendar.</div>
      </div>
      <div>
        <label className="mb-1 block text-[11px] uppercase tracking-wide text-muted">Send mail as</label>
        <Input size="sm" value={sendAs} onChange={(e) => setSendAs(e.target.value)} placeholder="support@yourdomain.com" />
        <div className="mt-1 text-[11px] text-muted">A verified send-as alias on the org account for outgoing mail. Blank = the account’s own address.</div>
      </div>
      <div className="flex items-center gap-3">
        <Button size="sm" onClick={() => void save()} disabled={!dirty}>Save</Button>
        {saved && <span className="text-xs text-[color:var(--theme-success)]">Saved</span>}
      </div>
    </div>
  )
}

// ui/src/routes/app/Admin.svelte
<script lang="ts">
  import { searchParams } from 'sv-router'
  import { useQueryClient } from '@tanstack/svelte-query'
  import Avatar from '@/components/ui/Avatar.svelte'
  import Checkbox from '@/components/ui/Checkbox.svelte'
  import Combobox from '@/components/ui/Combobox.svelte'
  import EmptyState from '@/components/ui/EmptyState.svelte'
  import Panel from '@/components/ui/Panel.svelte'
  import QueryError from '@/components/ui/QueryError.svelte'
  import SectionHeader from '@/components/ui/SectionHeader.svelte'
  import Select from '@/components/ui/Select.svelte'
  import Skeleton from '@/components/ui/Skeleton.svelte'
  import Tabs from '@/components/ui/Tabs.svelte'
  import { listQuery } from '@/components/ui/query-state'
  import RetrievalPanel from '@/components/admin/RetrievalPanel.svelte'
  import StoragePanel from '@/components/admin/StoragePanel.svelte'
  import SecretsPanel from '@/components/admin/SecretsPanel.svelte'
  import WorkspaceSecretsPanel from '@/components/admin/WorkspaceSecretsPanel.svelte'
  import { useAgents } from '@/lib/agents'
  import { useSession } from '@/lib/session'
  import { relativeTime } from '@/lib/fleet'
  import { fly, slide, staggerIn } from '@/lib/motion'
  import { GATEABLE_VIEWS, MANAGE_VIEWS } from '@/lib/nav'
  import { useEnabledApps } from '@/lib/apps'
  import AdminEmailPanel from './AdminEmailPanel.svelte'
  import AdminEncryptionPanel from './AdminEncryptionPanel.svelte'
  import AdminGithubPanel from './AdminGithubPanel.svelte'
  import AdminGuardrailsPanel from './AdminGuardrailsPanel.svelte'
  import AdminInstanceDomainPanel from './AdminInstanceDomainPanel.svelte'
  import AdminInvitesPanel from './AdminInvitesPanel.svelte'
  import AdminJudgePanel from './AdminJudgePanel.svelte'
  import AdminMemberDefaultsPanel from './AdminMemberDefaultsPanel.svelte'
  import AdminOrgGooglePanel from './AdminOrgGooglePanel.svelte'
  import AdminOrgPanel from './AdminOrgPanel.svelte'
  import AdminOutreachPanel from './AdminOutreachPanel.svelte'
  import AdminSettingsPanel from './AdminSettingsPanel.svelte'
  import AdminSignupDomainsPanel from './AdminSignupDomainsPanel.svelte'
  import AdminUserPermChips from './AdminUserPermChips.svelte'
  import { ADMIN_TABS, useAdminPermissions, useAdminUsers, type AdminTab } from './admin'

  // The admin console: people, their roles, and which agents each may use.
  const qc = useQueryClient()
  const session = useSession()
  const me = $derived(session.data)
  const usersQuery = useAdminUsers()
  const users = $derived(usersQuery.data)
  const permsQuery = useAdminPermissions()
  const perms = $derived(permsQuery.data)
  const fleetQuery = useAgents()
  const agentOptions = $derived((fleetQuery.data?.agents ?? []).map((a) => ({ value: a.id, label: a.label, sub: a.role })))
  // Enabled apps join the per-person view checklist as EXPLICIT grants —
  // every app view (work and manage) defaults denied for members; an admin
  // adds each one per person, same storage as core Manage views.
  // This one is not cosmetic. `allowedManageViews` is written back WHOLESALE
  // from `manageViews` below, so with the app list defaulted to `[]` a failed
  // /api/apps meant that toggling any unrelated view silently REVOKED every
  // app manage grant the person had — a permissions write derived from a read
  // that never happened.
  const appsList = listQuery(useEnabledApps(), { title: 'Could not load installed apps', variant: 'inline' })
  const enabledApps = $derived(appsList.rows)
  const appViews = $derived([
    ...enabledApps.filter((a) => a.surfaces.work).map((a) => ({ to: `/x/${a.slug}`, label: a.surfaces.work! })),
    ...enabledApps.filter((a) => a.surfaces.manage).map((a) => ({ to: `/x/${a.slug}/manage`, label: a.surfaces.manage! })),
  ])
  const workViews = GATEABLE_VIEWS
  const manageViews = $derived([...MANAGE_VIEWS.map((v) => ({ ...v, sub: 'manage' })), ...appViews.map((v) => ({ ...v, sub: 'app' }))])
  let error = $state<string | null>(null)

  const update = async (userId: string, patch: { role?: 'admin' | 'member'; agentModels?: string[]; canMintKeys?: boolean; deniedViews?: string[]; allowedManageViews?: string[]; assistantElevated?: boolean }) => {
    error = null
    const r = await fetch('/api/admin/users', {
      method: 'PUT',
      credentials: 'same-origin',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({ userId, ...patch }),
    })
    if (!r.ok) error = ((await r.json().catch(() => ({}))) as { error?: string }).error ?? 'update failed'
    await qc.invalidateQueries({ queryKey: ['admin-users'] })
  }

  // /admin?tab=security deep-links a concern.
  const tab: AdminTab = $derived.by(() => {
    const t = ADMIN_TABS.find((v) => v.id === searchParams.get('tab'))
    return t ? t.id : 'org'
  })
  const setTab = (t: AdminTab) => {
    if (t === 'org') searchParams.delete('tab')
    else searchParams.set('tab', t)
  }
</script>

{#if me && me.role !== 'admin'}
  <EmptyState icon="⛨" title="Admins only" hint="Ask an admin if you need access here." />
{:else}
  <div class="h-full overflow-y-auto p-8">
    <div class="mx-auto max-w-4xl space-y-6">
      <h1 class="text-2xl font-semibold tracking-tight text-fg">Admin</h1>

      <!-- One concern per tab; every panel keeps its own component. -->
      <Tabs items={ADMIN_TABS} value={tab} onChange={setTab} />

      <!-- Tab-pane grammar: pane rises in on switch (no exit), panels stagger —
           these are section stacks, one Panel per concern. -->
      {#key tab}
      <div in:fly={{ y: 6, duration: 200 }} use:staggerIn class="space-y-6">
      {#if tab === 'org'}
        <AdminOrgPanel />
        <AdminInstanceDomainPanel />
        <AdminSignupDomainsPanel />
        <AdminEmailPanel />
        <AdminGithubPanel />
        <AdminOrgGooglePanel />
      {/if}
      {#if tab === 'agents'}
        <AdminJudgePanel />
        <AdminGuardrailsPanel />
        <AdminOutreachPanel />
      {/if}
      {#if tab === 'retrieval'}<RetrievalPanel />{/if}
      {#if tab === 'storage'}<StoragePanel />{/if}
      <!-- TWO DIFFERENT NOUNS ON ONE TAB, in the order an operator needs them: the
           inventory answers "is this instance healthy", the panel below answers
           "what may my agents spend". Sharing a tab is right — they are both
           credentials — and sharing a heading would not be. -->
      {#if tab === 'secrets'}<SecretsPanel />{/if}
      {#if tab === 'secrets'}<WorkspaceSecretsPanel />{/if}
      {#if tab === 'security'}
        <AdminEncryptionPanel />
        <AdminSettingsPanel />
      {/if}
      {#if tab === 'people'}<AdminInvitesPanel />{/if}
      {#if tab === 'people'}
        {#if perms}
          <AdminMemberDefaultsPanel {perms} />
        {:else if permsQuery.isError}
          <!-- Silence here reads as "no permission model configured". Say so. -->
          <Panel>
            <QueryError
              variant="compact"
              error={permsQuery.error}
              title="Could not load member permissions"
              onRetry={() => void permsQuery.refetch()}
            />
          </Panel>
        {/if}
      {/if}
      {#if tab === 'people'}
        <Panel>
          <SectionHeader
            class="mb-4"
            title="People"
            info="Roles, per-person agent access, and which views each member can reach. Empty = all (open by default); pick any to restrict. Admins always have full access."
          />
          {#if error}
            <div transition:slide={{ duration: 150 }} class="mb-2 text-xs text-danger">
              {error}
            </div>
          {/if}
          {#if usersQuery.isPending}
            <!-- Person-row skeletons: avatar + name/email bars + the role/keys
                 controls, so the resolved list lands without a jump. -->
            <div class="divide-y divide-line-subtle">
              {#each Array.from({ length: 4 }, (_, i) => i) as i (i)}
                <div class="flex items-center gap-3 py-3">
                  <Skeleton class="h-7 w-7 shrink-0 rounded-full" delay={i * 0.12} />
                  <div class="min-w-0 flex-1 space-y-1.5">
                    <Skeleton class="h-2.5 w-36 rounded-full" delay={i * 0.12} />
                    <Skeleton class="h-2 w-48 rounded-full" delay={i * 0.12 + 0.06} />
                  </div>
                  <Skeleton class="h-7 w-28 shrink-0" delay={i * 0.12} />
                  <Skeleton class="h-4 w-12 shrink-0" delay={i * 0.12} />
                  <Skeleton class="h-2.5 w-16 shrink-0 rounded-full" delay={i * 0.12} />
                </div>
              {/each}
            </div>
          {:else if !users}
            <!-- The most dangerous empty render on the whole surface: an admin
                 seeing no rows concludes the org is empty (or that a person they
                 just off-boarded is gone) when the read simply failed. -->
            <QueryError
              variant="compact"
              error={usersQuery.error}
              title="Could not load your people"
              onRetry={() => void usersQuery.refetch()}
            />
          {:else}
            <ul class="divide-y divide-line-subtle">
              {#each users as u (u.id)}
                <!-- One ALLOW list spanning both worlds: work views default in
                     (denials stored), Manage views default out (allows stored). -->
                {@const allowedViews = [
                  ...workViews.filter((v) => !u.deniedViews.includes(v.to)).map((v) => v.to),
                  ...manageViews.filter((v) => u.allowedManageViews.includes(v.to)).map((v) => v.to),
                ]}
                <li class="-mx-2 space-y-2 rounded-md px-2 py-3 transition-colors hover:bg-hover">
                  <div class="flex items-center gap-3">
                    <Avatar name={u.name ?? u.email} class="h-7 w-7" />
                    <span class="min-w-0 flex-1">
                      <span class="block truncate text-sm text-fg">{u.name ?? u.email ?? u.id}</span>
                      <span class="block truncate text-xs text-muted">
                        {u.name && u.email ? u.email : `seen ${relativeTime(u.lastSeenAt)}`}
                      </span>
                    </span>
                    <Select
                      value={u.role}
                      size="sm"
                      disabled={u.pinnedAdmin || u.id === me?.id}
                      title={u.pinnedAdmin ? 'Pinned admin via AUTH_ADMIN_EMAILS' : u.id === me?.id ? 'You cannot demote yourself' : undefined}
                      onchange={(e) => void update(u.id, { role: e.currentTarget.value as 'admin' | 'member' })}
                      class="w-28 shrink-0"
                    >
                      <option value="member">Member</option>
                      <option value="admin">Admin</option>
                    </Select>
                    {#if u.role === 'admin' && u.assistantModel}
                      <Checkbox
                        class="shrink-0"
                        title={`Give ${u.assistantModel} org-wide view/edit: every board, every channel and relay (never DMs), and editor rights on all org-visible knowledge and artifacts. Only while this user is an admin.`}
                        checked={u.assistantElevated}
                        onChange={(checked) => void update(u.id, { assistantElevated: checked })}
                        label="elevated assistant"
                      />
                    {/if}
                    <span class="w-16 shrink-0 text-right font-mono text-[10px] tracking-[0.05em] text-muted">{relativeTime(u.lastSeenAt)}</span>
                  </div>
                  {#if u.role !== 'admin'}
                    <div class="flex items-center gap-2 pl-10">
                      <Combobox
                        options={agentOptions}
                        selected={u.agentModels}
                        onChange={(models) => void update(u.id, { agentModels: models })}
                        multiple
                        size="sm"
                        placeholder="All agents"
                        class="min-w-0 flex-1"
                      />
                      <Combobox
                        options={[
                          ...workViews.map((v) => ({ value: v.to, label: v.label, sub: 'work' })),
                          ...manageViews.map((v) => ({ value: v.to, label: v.label, sub: v.sub })),
                        ]}
                        selected={allowedViews}
                        onChange={(views) =>
                          void update(u.id, {
                            deniedViews: workViews.filter((v) => !views.includes(v.to)).map((v) => v.to),
                            allowedManageViews: manageViews.filter((v) => views.includes(v.to)).map((v) => v.to),
                          })}
                        multiple
                        size="sm"
                        disabled={appsList.failed}
                        placeholder="Work views"
                        class="min-w-0 flex-1"
                      />
                      <!-- ^ Editing writes the whole allow-list back. While the
                           app views are missing, that write would drop them. -->
                    </div>
                    {#if appsList.notice}<div class="pl-10"><QueryError {...appsList.notice} /></div>{/if}
                    {#if perms}<AdminUserPermChips userId={u.id} {perms} />{/if}
                  {/if}
                </li>
              {/each}
            </ul>
          {/if}
        </Panel>
      {/if}
      </div>
      {/key}
    </div>
  </div>
{/if}
