// ui/src/components/ui/ContextMenu.svelte
<script lang="ts">
  import { cn } from '@/lib/cn'
  import { portal } from '@/lib/portal'
  import { fade, scale, POP, QUICK } from '@/lib/motion'
  import { popPanel } from '@/components/chat/chat-chrome'
  import type { ContextMenuController, ContextMenuItem, MenuIcon } from './context-menu.svelte'

  // Renders the open menu of a `useContextMenu()` controller (this was the
  // `menu` JSX the React hook returned). Mount once per surface:
  //   <ContextMenu {menu} />
  // See context-menu.svelte.ts for the item grammar and usage.

  let { menu }: { menu: ContextMenuController } = $props()

  let el = $state<HTMLDivElement | null>(null)
  let active = $state(-1)
  let openSub = $state<number | null>(null)

  const selectable = $derived(
    (menu.state?.items ?? []).filter((i): i is ContextMenuItem => i !== 'sep' && !i.disabled),
  )

  // Rows with their selectable index precomputed (the React version ran a
  // mutable counter inline in the JSX; the template can't).
  const rows = $derived.by(() => {
    let selIdx = -1
    return (menu.state?.items ?? []).map((item, i) => {
      if (item !== 'sep' && !item.disabled) selIdx += 1
      return { item, i, idx: item !== 'sep' && !item.disabled ? selIdx : -1 }
    })
  })

  // Fresh menu, fresh keyboard/submenu state (the React version got this by
  // remounting the Menu component on every open).
  $effect(() => {
    void menu.state
    active = -1
    openSub = null
  })

  // Clamp inside the viewport once we know our size. offsetWidth/Height, not
  // getBoundingClientRect — the entrance scale would skew a rect measured
  // mid-transition.
  $effect(() => {
    const st = menu.state
    const node = el
    if (!st || !node) return
    if (st.x + node.offsetWidth > window.innerWidth - 8) node.style.left = `${Math.max(8, window.innerWidth - node.offsetWidth - 8)}px`
    if (st.y + node.offsetHeight > window.innerHeight - 8) node.style.top = `${Math.max(8, window.innerHeight - node.offsetHeight - 8)}px`
  })

  function onDocMousedown(e: MouseEvent) {
    if (!menu.state) return
    if (!el?.contains(e.target as Node)) menu.closeMenu()
  }

  function onDocKeydown(e: KeyboardEvent) {
    if (!menu.state) return
    if (e.key === 'Escape') {
      e.stopPropagation()
      menu.closeMenu()
    } else if (e.key === 'ArrowDown') {
      e.preventDefault()
      active = (active + 1) % selectable.length
    } else if (e.key === 'ArrowUp') {
      e.preventDefault()
      active = (active - 1 + selectable.length) % selectable.length
    } else if (e.key === 'Enter' && active >= 0) {
      e.preventDefault()
      const it = selectable[active]
      if (it && !it.children?.length) {
        it.onSelect?.()
        menu.closeMenu()
      }
    }
  }

  function onDocScroll() {
    if (menu.state) menu.closeMenu()
  }
</script>

{#snippet menuIcon(icon: MenuIcon)}
  {#if Array.isArray(icon)}
    {@const [IconC, iconProps] = icon}
    <IconC {...iconProps} />
  {:else}
    {@render icon()}
  {/if}
{/snippet}

<svelte:document onmousedown={onDocMousedown} onkeydowncapture={onDocKeydown} onscrollcapture={onDocScroll} />

{#if menu.state}
  {@const st = menu.state}
  <div
    bind:this={el}
    use:portal
    role="menu"
    style="position: fixed; left: {st.x}px; top: {st.y}px; z-index: 80"
    class={cn(popPanel, 'min-w-44')}
    oncontextmenu={(e) => e.preventDefault()}
    in:scale={POP}
    out:fade={QUICK}
  >
    {#each rows as { item, i, idx } (item === 'sep' ? `s${i}` : `${item.label}${i}`)}
      {#if item === 'sep'}
        <div class="mx-2 my-1 border-t border-line"></div>
      {:else}
        {@const hasKids = !!item.children?.length}
        <!-- svelte-ignore a11y_no_static_element_interactions -->
        <div
          class="relative"
          onmouseleave={() => {
            if (hasKids && openSub === i) openSub = null
          }}
        >
          <button
            type="button"
            role="menuitem"
            disabled={item.disabled}
            aria-haspopup={hasKids || undefined}
            onmouseenter={() => {
              if (item.disabled) return
              active = idx
              openSub = hasKids ? i : null
            }}
            onclick={() => {
              if (hasKids) {
                openSub = openSub === i ? null : i
                return
              }
              item.onSelect?.()
              menu.closeMenu()
            }}
            class={cn(
              'flex w-full items-center gap-2.5 rounded-md px-2.5 py-1.5 text-left font-sans text-[13px] transition-colors',
              item.disabled
                ? 'cursor-default text-muted opacity-50'
                : item.danger
                  ? cn('text-danger', active === idx && 'bg-danger/10')
                  : cn('text-fg', (active === idx || openSub === i) && 'bg-hover'),
            )}
          >
            {#if item.checked !== undefined}
              <span class="grid w-4 shrink-0 place-items-center text-accent">{item.checked ? '✓' : ''}</span>
            {:else if item.icon}
              <span class="grid w-4 shrink-0 place-items-center text-muted">{@render menuIcon(item.icon)}</span>
            {/if}
            <span class="min-w-0 flex-1 truncate">{item.label}</span>
            {#if hasKids}
              <span class="shrink-0 text-xs text-muted">▸</span>
            {/if}
          </button>
          {#if hasKids && openSub === i}
            <div class={cn(popPanel, 'absolute left-full top-0 z-10 -ml-0.5 min-w-40')} in:scale={POP} out:fade={QUICK}>
              {#each item.children ?? [] as kid, k (kid === 'sep' ? `ks${k}` : `${kid.label}${k}`)}
                {#if kid === 'sep'}
                  <div class="mx-2 my-1 border-t border-line"></div>
                {:else}
                  <button
                    type="button"
                    role="menuitem"
                    disabled={kid.disabled}
                    onclick={() => {
                      kid.onSelect?.()
                      menu.closeMenu()
                    }}
                    class={cn(
                      'flex w-full items-center gap-2.5 rounded-md px-2.5 py-1.5 text-left font-sans text-[13px] transition-colors',
                      kid.disabled
                        ? 'cursor-default text-muted opacity-50'
                        : kid.danger
                          ? 'text-danger hover:bg-danger/10'
                          : 'text-fg hover:bg-hover',
                    )}
                  >
                    {#if kid.checked !== undefined}
                      <span class="grid w-4 shrink-0 place-items-center text-accent">{kid.checked ? '✓' : ''}</span>
                    {:else if kid.icon}
                      <span class="grid w-4 shrink-0 place-items-center text-muted">{@render menuIcon(kid.icon)}</span>
                    {/if}
                    <span class="min-w-0 flex-1 truncate">{kid.label}</span>
                  </button>
                {/if}
              {/each}
            </div>
          {/if}
        </div>
      {/if}
    {/each}
  </div>
{/if}

// ui/src/components/ui/context-menu.tsx
import { useCallback, useEffect, useRef, useState, type ReactNode } from 'react'
import { createPortal } from 'react-dom'
import { cn } from '@/lib/cn'

// The one context menu. Right-click a row/card/tile → its actions at the
// cursor. Same shell as dropdown menus (rounded-xl border bg-card p-1
// shadow-lg); portaled to <body> so backdrop-filter surfaces can't trap the
// fixed positioning. Esc / outside-click / scroll close it.
//
// Usage:
//   const { openMenu, menu } = useContextMenu()
//   <div onContextMenu={(e) => openMenu(e, [
//     { label: 'Open', onSelect: ... },
//     'sep',
//     { label: 'Delete', danger: true, onSelect: ... },
//   ])}>…</div>
//   {menu}
//
// Items should mirror actions the surface already offers — a context menu is
// a shortcut, never the only home of an action.

export interface ContextMenuItem {
  label: string
  icon?: ReactNode
  danger?: boolean
  disabled?: boolean
  /** Marks the current choice in a submenu (renders a leading check). */
  checked?: boolean
  /** Submenu — hover opens a flyout of these entries. `onSelect` is ignored
   *  on items that carry children. */
  children?: ContextMenuEntry[]
  onSelect?: () => void
}
export type ContextMenuEntry = ContextMenuItem | 'sep'

interface MenuState {
  x: number
  y: number
  items: ContextMenuEntry[]
}

export function useContextMenu() {
  const [state, setState] = useState<MenuState | null>(null)

  const openMenu = useCallback((e: React.MouseEvent, items: ContextMenuEntry[]) => {
    e.preventDefault()
    e.stopPropagation()
    const real = items.filter((i) => i !== 'sep')
    if (real.length === 0) return
    setState({ x: e.clientX, y: e.clientY, items })
  }, [])

  const close = useCallback(() => setState(null), [])

  return {
    openMenu,
    closeMenu: close,
    menu: state ? <Menu state={state} onClose={close} /> : null,
  }
}

function Menu({ state, onClose }: { state: MenuState; onClose: () => void }) {
  const ref = useRef<HTMLDivElement>(null)
  const [active, setActive] = useState(-1)
  const [openSub, setOpenSub] = useState<number | null>(null)
  const selectable = state.items.filter((i): i is ContextMenuItem => i !== 'sep' && !i.disabled)

  // Clamp inside the viewport once we know our size.
  useEffect(() => {
    const el = ref.current
    if (!el) return
    const r = el.getBoundingClientRect()
    if (state.x + r.width > window.innerWidth - 8) el.style.left = `${Math.max(8, window.innerWidth - r.width - 8)}px`
    if (state.y + r.height > window.innerHeight - 8) el.style.top = `${Math.max(8, window.innerHeight - r.height - 8)}px`
  }, [state])

  useEffect(() => {
    const onDown = (e: MouseEvent) => {
      if (!ref.current?.contains(e.target as Node)) onClose()
    }
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        e.stopPropagation()
        onClose()
      } else if (e.key === 'ArrowDown') {
        e.preventDefault()
        setActive((a) => (a + 1) % selectable.length)
      } else if (e.key === 'ArrowUp') {
        e.preventDefault()
        setActive((a) => (a - 1 + selectable.length) % selectable.length)
      } else if (e.key === 'Enter' && active >= 0) {
        e.preventDefault()
        const it = selectable[active]
        if (it && !it.children?.length) {
          it.onSelect?.()
          onClose()
        }
      }
    }
    const onScroll = () => onClose()
    document.addEventListener('mousedown', onDown)
    document.addEventListener('keydown', onKey, true)
    document.addEventListener('scroll', onScroll, true)
    return () => {
      document.removeEventListener('mousedown', onDown)
      document.removeEventListener('keydown', onKey, true)
      document.removeEventListener('scroll', onScroll, true)
    }
  }, [onClose, active, selectable])

  if (typeof document === 'undefined') return null
  let selIdx = -1
  return createPortal(
    <div
      ref={ref}
      role="menu"
      style={{ position: 'fixed', left: state.x, top: state.y, zIndex: 80 }}
      className="min-w-44 rounded-xl border border-line bg-card p-1 shadow-lg"
      onContextMenu={(e) => e.preventDefault()}
    >
      {state.items.map((item, i) => {
        if (item === 'sep') return <div key={`s${i}`} className="mx-2 my-1 border-t border-line-subtle" />
        if (!item.disabled) selIdx += 1
        const idx = selIdx
        const hasKids = !!item.children?.length
        return (
          <div key={`${item.label}${i}`} className="relative" onMouseLeave={() => hasKids && setOpenSub((s) => (s === i ? null : s))}>
            <button
              type="button"
              role="menuitem"
              disabled={item.disabled}
              aria-haspopup={hasKids || undefined}
              onMouseEnter={() => {
                if (item.disabled) return
                setActive(idx)
                setOpenSub(hasKids ? i : null)
              }}
              onClick={() => {
                if (hasKids) return setOpenSub((s) => (s === i ? null : i))
                item.onSelect?.()
                onClose()
              }}
              className={cn(
                'flex w-full items-center gap-2.5 rounded-lg px-2.5 py-1.5 text-left text-sm transition-colors',
                item.disabled
                  ? 'cursor-default text-muted opacity-50'
                  : item.danger
                    ? cn('text-[color:var(--theme-danger)]', active === idx && 'bg-[color:var(--theme-danger)]/10')
                    : cn('text-fg', (active === idx || openSub === i) && 'bg-sidebar'),
              )}
            >
              {item.checked !== undefined ? (
                <span className="grid w-4 shrink-0 place-items-center text-accent">{item.checked ? '✓' : ''}</span>
              ) : (
                item.icon && <span className="grid w-4 shrink-0 place-items-center text-muted">{item.icon}</span>
              )}
              <span className="min-w-0 flex-1 truncate">{item.label}</span>
              {hasKids && <span className="shrink-0 text-xs text-muted">▸</span>}
            </button>
            {hasKids && openSub === i && (
              <div className="absolute left-full top-0 z-10 -ml-0.5 min-w-40 rounded-xl border border-line bg-card p-1 shadow-lg">
                {item.children!.map((kid, k) => {
                  if (kid === 'sep') return <div key={`ks${k}`} className="mx-2 my-1 border-t border-line-subtle" />
                  return (
                    <button
                      key={`${kid.label}${k}`}
                      type="button"
                      role="menuitem"
                      disabled={kid.disabled}
                      onClick={() => {
                        kid.onSelect?.()
                        onClose()
                      }}
                      className={cn(
                        'flex w-full items-center gap-2.5 rounded-lg px-2.5 py-1.5 text-left text-sm transition-colors',
                        kid.disabled
                          ? 'cursor-default text-muted opacity-50'
                          : kid.danger
                            ? 'text-[color:var(--theme-danger)] hover:bg-[color:var(--theme-danger)]/10'
                            : 'text-fg hover:bg-sidebar',
                      )}
                    >
                      {kid.checked !== undefined ? (
                        <span className="grid w-4 shrink-0 place-items-center text-accent">{kid.checked ? '✓' : ''}</span>
                      ) : (
                        kid.icon && <span className="grid w-4 shrink-0 place-items-center text-muted">{kid.icon}</span>
                      )}
                      <span className="min-w-0 flex-1 truncate">{kid.label}</span>
                    </button>
                  )
                })}
              </div>
            )}
          </div>
        )
      })}
    </div>,
    document.body,
  )
}

// Re-export from its real home (lib) — kit files hold no app URL logic.
export { copyAppLink } from '@/lib/links'

/** Anchored dropdown menu — the SAME shell and item grammar as the context
 *  menu, attached to a trigger instead of the cursor. Replaces every ad-hoc
 *  `absolute top-full … rounded-xl border bg-card p-1` panel. */
export function DropdownMenu({
  trigger,
  items,
  align = 'right',
  className,
}: {
  /** Renders the trigger; `open` lets it style its active state. */
  trigger: (open: boolean) => ReactNode
  items: ContextMenuEntry[] | (() => ContextMenuEntry[])
  align?: 'left' | 'right'
  className?: string
}) {
  const [open, setOpen] = useState(false)
  const ref = useRef<HTMLDivElement>(null)

  useEffect(() => {
    if (!open) return
    const onDown = (e: MouseEvent) => {
      if (!ref.current?.contains(e.target as Node)) setOpen(false)
    }
    const onKey = (e: KeyboardEvent) => e.key === 'Escape' && setOpen(false)
    document.addEventListener('mousedown', onDown)
    document.addEventListener('keydown', onKey)
    return () => {
      document.removeEventListener('mousedown', onDown)
      document.removeEventListener('keydown', onKey)
    }
  }, [open])

  const entries = typeof items === 'function' ? (open ? items() : []) : items
  return (
    <div ref={ref} className={cn('relative', className)}>
      <span onClick={() => setOpen((o) => !o)}>{trigger(open)}</span>
      {open && (
        <div
          role="menu"
          className={cn('absolute top-full z-40 mt-1 min-w-44 rounded-xl border border-line bg-card p-1 shadow-lg', align === 'right' ? 'right-0' : 'left-0')}
        >
          {entries.map((item, i) => {
            if (item === 'sep') return <div key={`s${i}`} className="mx-2 my-1 border-t border-line-subtle" />
            return (
              <button
                key={`${item.label}${i}`}
                type="button"
                role="menuitem"
                disabled={item.disabled}
                onClick={() => {
                  item.onSelect?.()
                  setOpen(false)
                }}
                className={cn(
                  'flex w-full items-center gap-2.5 rounded-lg px-2.5 py-1.5 text-left text-sm transition-colors',
                  item.disabled
                    ? 'cursor-default text-muted opacity-50'
                    : item.danger
                      ? 'text-[color:var(--theme-danger)] hover:bg-[color:var(--theme-danger)]/10'
                      : 'text-fg hover:bg-sidebar',
                )}
              >
                {item.icon && <span className="grid w-4 shrink-0 place-items-center text-muted">{item.icon}</span>}
                <span className="min-w-0 flex-1 truncate">{item.label}</span>
              </button>
            )
          })}
        </div>
      )}
    </div>
  )
}
