// ui/src/components/ui/save-button.tsx
// The one "Save → Saved ✓" pattern. useSavedFlash gives the timed flag;
// SaveButton bundles it with the standard button + confirmation copy so
// settings panels stop re-rolling setTimeout state machines.
import { useEffect, useRef, useState } from 'react'
import { Button, type ButtonProps } from './button'
import { cn } from '@/lib/cn'

export function useSavedFlash(ms = 1500): { saved: boolean; flash: () => void } {
  const [saved, setSaved] = useState(false)
  const t = useRef<ReturnType<typeof setTimeout> | null>(null)
  useEffect(
    () => () => {
      if (t.current) clearTimeout(t.current)
    },
    [],
  )
  return {
    saved,
    flash: () => {
      setSaved(true)
      if (t.current) clearTimeout(t.current)
      t.current = setTimeout(() => setSaved(false), ms)
    },
  }
}

/** Runs `onSave`, disables while pending, flashes "Saved". */
export function SaveButton({
  onSave,
  children = 'Save',
  className,
  disabled,
  ...rest
}: Omit<ButtonProps, 'onClick'> & { onSave: () => Promise<unknown> | unknown }) {
  const [busy, setBusy] = useState(false)
  const { saved, flash } = useSavedFlash()
  return (
    <span className={cn('inline-flex items-center gap-2', className)}>
      <Button
        {...rest}
        disabled={disabled || busy}
        onClick={() => {
          setBusy(true)
          void Promise.resolve(onSave())
            .then(() => flash())
            .finally(() => setBusy(false))
        }}
      >
        {children}
      </Button>
      {/* Confirmation reads as mono telemetry in the success signal (spec §8). */}
      {saved && (
        <span className="font-mono text-[10px] uppercase tracking-[0.05em] text-success">Saved</span>
      )}
    </span>
  )
}

// ui/src/components/ui/SaveButton.svelte
<script lang="ts">
  import type { HTMLButtonAttributes } from 'svelte/elements'
  import type { ButtonVariant } from './button'
  import type { ControlSize } from './control'
  import Button from './Button.svelte'
  import { cn } from '@/lib/cn'
  import { useSavedFlash } from './save-button.svelte'

  interface Props extends Omit<HTMLButtonAttributes, 'onclick'> {
    variant?: ButtonVariant
    size?: ControlSize
    onSave: () => Promise<unknown> | unknown
  }

  // Runs `onSave`, disables while pending, flashes "Saved".
  let { onSave, children, class: className, disabled, ...rest }: Props = $props()

  let busy = $state(false)
  const flash = useSavedFlash()
</script>

<span class={cn('inline-flex items-center gap-2', className)}>
  <Button
    {...rest}
    disabled={disabled || busy}
    onclick={() => {
      busy = true
      void Promise.resolve(onSave())
        .then(() => flash.flash())
        .finally(() => (busy = false))
    }}
  >
    {#if children}{@render children()}{:else}Save{/if}
  </Button>
  <!-- Confirmation reads as mono telemetry in the success signal (spec §8). -->
  {#if flash.saved}
    <span class="font-mono text-[10px] uppercase tracking-[0.05em] text-success">Saved</span>
  {/if}
</span>
