// ui/src/components/brand.tsx
import { cn } from '@/lib/cn'

// The Talaria brand — gold "A"-delta mark + spaced-caps wordmark
// (Mercury spec §4, exact SVG from the design file).
export function Brand({ className, showTag = false }: { className?: string; showTag?: boolean }) {
  return (
    <div className={cn('flex items-center gap-2.5', className)}>
      <WingMark className="h-5 w-5" />
      <div className="leading-tight">
        <div className="font-sans text-[13px] leading-4 font-semibold tracking-[0.18em] text-fg">
          TALARIA
        </div>
        {showTag && (
          <div className="theme-muted text-[11px] tracking-wide">the winged fleet cockpit</div>
        )}
      </div>
    </div>
  )
}

// The notched-triangle "A"-delta glyph in flat warm gold.
export function WingMark({ className }: { className?: string }) {
  return (
    <svg viewBox="0 0 20 20" className={className} aria-hidden>
      <path d="M10 2L18 18H12.6L10 12.4L7.4 18H2L10 2Z" fill="var(--theme-accent)" />
    </svg>
  )
}

// ui/src/components/Brand.svelte
<script lang="ts">
  import { cn } from '@/lib/cn'
  import WingMark from './WingMark.svelte'

  // The Talaria brand — gold "A"-delta mark + spaced-caps wordmark
  // (Mercury spec §4, exact SVG from the design file).
  let { class: className, showTag = false }: { class?: string; showTag?: boolean } = $props()
</script>

<div class={cn('flex items-center gap-2.5', className)}>
  <WingMark class="h-5 w-5" />
  <div class="leading-tight">
    <div class="font-sans text-[13px] leading-4 font-semibold tracking-[0.18em] text-fg">
      TALARIA
    </div>
    {#if showTag}
      <div class="theme-muted text-[11px] tracking-wide">the winged fleet cockpit</div>
    {/if}
  </div>
</div>
