// ui/src/components/mercury-backdrop.tsx
// Mercury is matte: the backdrop is the flat ground surface — no grids,
// no glows, no drifting blooms. Kept as a component so existing layout
// imports (_app.tsx, login, join) stay stable.
export function MercuryBackdrop() {
  return <div aria-hidden className="pointer-events-none fixed inset-0 -z-10 bg-surface" />
}

// ui/src/components/MercuryBackdrop.svelte
<script lang="ts">
  // Mercury is matte: the backdrop is the flat ground surface — no grids,
  // no glows, no drifting blooms. Kept as a component so existing layout
  // imports (the _app layout, login, join) stay stable.
  // (The script block exists so TS importers see a typed module.)
</script>
<div aria-hidden="true" class="pointer-events-none fixed inset-0 -z-10 bg-surface"></div>
