// ui/src/components/inbox/inbox-chat-panel.tsx
import {
  forwardRef,
  useCallback,
  useEffect,
  useImperativeHandle,
  useMemo,
  useRef,
  useState,
  useSyncExternalStore,
  type KeyboardEvent as ReactKeyboardEvent,
  type PointerEvent as ReactPointerEvent,
} from 'react'
import {
  Bot,
  ChevronLeft,
  ChevronRight,
  ExternalLink,
  GripVertical,
  MessageSquareText,
  Paperclip,
  RotateCcw,
  X,
} from 'lucide-react'
import { AgentChip } from '@/components/chat/agent-picker'
import { ChatComposer, type ChatComposerHandle } from '@/components/chat/chat-composer'
import { TierPicker } from '@/components/chat/tier-picker'
import { Button, buttonClasses } from '@/components/ui/button'
import { Markdown } from '@/components/ui/markdown'
import { Skeleton } from '@/components/ui/skeleton'
import { cn } from '@/lib/cn'
import { useAgents } from '@/lib/agents'
import { mergeInboxTimelinePages } from '@/lib/inbox-focus-timeline'
import {
  DEFAULT_INBOX_PANEL_WIDTH,
  MAX_INBOX_PANEL_WIDTH,
  MIN_INBOX_PANEL_WIDTH,
  clampInboxPanelWidth,
  shouldCollapseInboxPanel,
} from '@/lib/inbox-panel-size'
import {
  useInboxFocusConversation,
  type FocusAssistant,
  type FocusItem,
  type InboxTimelineEntry,
} from '@/lib/inbox-focus'

const PANEL_COLLAPSED_KEY = 'talaria:inbox-chat-collapsed'
const PANEL_COLLAPSED_EVENT = 'talaria:inbox-chat-collapsed'
const PANEL_WIDTH_KEY = 'talaria:inbox-chat-width'
let collapsedFallback = false
let widthFallback = DEFAULT_INBOX_PANEL_WIDTH

function readPanelCollapsed(): boolean {
  try {
    return window.localStorage.getItem(PANEL_COLLAPSED_KEY) === '1'
  } catch {
    return collapsedFallback
  }
}

function subscribePanelCollapsed(onChange: () => void): () => void {
  window.addEventListener(PANEL_COLLAPSED_EVENT, onChange)
  window.addEventListener('storage', onChange)
  return () => {
    window.removeEventListener(PANEL_COLLAPSED_EVENT, onChange)
    window.removeEventListener('storage', onChange)
  }
}

function usePanelCollapsed() {
  const collapsed = useSyncExternalStore(subscribePanelCollapsed, readPanelCollapsed, () => false)
  const setCollapsed = useCallback((next: boolean) => {
    collapsedFallback = next
    try {
      window.localStorage.setItem(PANEL_COLLAPSED_KEY, next ? '1' : '0')
    } catch {
      /* private mode: keep the in-memory preference for this tab */
    }
    window.dispatchEvent(new Event(PANEL_COLLAPSED_EVENT))
  }, [])
  return { collapsed, setCollapsed }
}

function readPanelWidth(): number {
  try {
    const stored = window.localStorage.getItem(PANEL_WIDTH_KEY)
    return stored === null ? widthFallback : clampInboxPanelWidth(Number(stored))
  } catch {
    return widthFallback
  }
}

function usePanelWidth() {
  const [width, setLocalWidth] = useState(DEFAULT_INBOX_PANEL_WIDTH)
  const committedWidthRef = useRef(DEFAULT_INBOX_PANEL_WIDTH)

  useEffect(() => {
    const syncWidth = () => {
      const next = readPanelWidth()
      committedWidthRef.current = next
      setLocalWidth((current) => current === next ? current : next)
    }
    const syncStoredWidth = (event: StorageEvent) => {
      if (event.key === PANEL_WIDTH_KEY) syncWidth()
    }
    syncWidth()
    window.addEventListener('storage', syncStoredWidth)
    return () => window.removeEventListener('storage', syncStoredWidth)
  }, [])

  const setWidth = useCallback((next: number) => {
    const clamped = clampInboxPanelWidth(next)
    if (clamped === committedWidthRef.current) return
    committedWidthRef.current = clamped
    widthFallback = clamped
    setLocalWidth(clamped)
    try {
      window.localStorage.setItem(PANEL_WIDTH_KEY, String(clamped))
    } catch {
      /* private mode: keep the in-memory preference for this tab */
    }
  }, [])
  return { width, setWidth }
}

export interface InboxChatPanelHandle {
  focus: () => void
  expand: () => void
  insertText: (text: string) => void
}

interface StreamingTurn {
  user: string
  status: string
  content: string
}

export const InboxChatPanel = forwardRef<
  InboxChatPanelHandle,
  {
    active: FocusItem | null
    focusMode: boolean
    assistant: FocusAssistant | undefined
    busy: boolean
    notice: string | null
    streaming: StreamingTurn | null
    onSubmit: (instruction: string, options: { focusKey: string | null; delegateModel: string | null; delegateTier: string | null }) => void
    onConfirm: (entry: Extract<InboxTimelineEntry, { kind: 'activity' }>) => void
    onCancel: (entry: Extract<InboxTimelineEntry, { kind: 'activity' }>) => void
    onRetry: (entry: Extract<InboxTimelineEntry, { kind: 'activity' }>) => void
    onUndo: (entry: Extract<InboxTimelineEntry, { kind: 'activity' }>) => void
  }
>(function InboxChatPanel(
  { active, focusMode, assistant, busy, notice, streaming, onSubmit, onConfirm, onCancel, onRetry, onUndo },
  ref,
) {
  const { collapsed, setCollapsed } = usePanelCollapsed()
  const { width: savedWidth, setWidth: setSavedWidth } = usePanelWidth()
  const conversation = useInboxFocusConversation()
  const { data: agentData, isLoading: agentsLoading } = useAgents()
  const [delegateModel, setDelegateModel] = useState('')
  const [tier, setTier] = useState('')
  const [detachedKey, setDetachedKey] = useState<string | null>(null)
  const [hiddenOutput, setHiddenOutput] = useState(false)
  const [dragWidth, setDragWidth] = useState<number | null>(null)
  const composerRef = useRef<ChatComposerHandle>(null)
  const expandButtonRef = useRef<HTMLButtonElement>(null)
  const scrollerRef = useRef<HTMLDivElement>(null)
  const pinnedRef = useRef(true)
  const lastOutputRef = useRef<string | null>(null)
  const resizeRef = useRef<{
    pointerId: number
    startX: number
    startWidth: number
    latestRawWidth: number
  } | null>(null)
  const resizeFrameRef = useRef<number | null>(null)
  const pendingDragWidthRef = useRef<number | null>(null)
  const attached = Boolean(active && detachedKey !== active.key)
  const toggleActiveDecisionAttachment = useCallback(() => {
    if (!active) return
    setDetachedKey((current) => current === active.key ? null : active.key)
  }, [active])
  const panelWidth = dragWidth ?? savedWidth
  const resizing = dragWidth !== null

  const entries = useMemo(
    () => mergeInboxTimelinePages((conversation.data?.pages ?? []).map((page) => page.entries)),
    [conversation.data?.pages],
  )

  const agents = useMemo(
    () => [
      {
        id: '',
        label: assistant?.name ?? 'Scout',
        role: assistant?.configured ? 'Personal orchestrator' : 'Not configured',
      },
      ...(agentData?.agents ?? []).filter((agent) => agent.id !== assistant?.model),
    ],
    [agentData?.agents, assistant],
  )
  const selectedAgent = agentData?.agents.find((agent) => agent.id === delegateModel)

  const expand = useCallback(() => {
    setCollapsed(false)
    setHiddenOutput(false)
    window.setTimeout(() => composerRef.current?.focus(), 0)
  }, [setCollapsed])
  const collapse = useCallback(() => {
    setCollapsed(true)
    window.setTimeout(() => expandButtonRef.current?.focus(), 0)
  }, [setCollapsed])

  const beginResize = (event: ReactPointerEvent<HTMLDivElement>) => {
    if (event.button !== 0) return
    event.preventDefault()
    resizeRef.current = {
      pointerId: event.pointerId,
      startX: event.clientX,
      startWidth: panelWidth,
      latestRawWidth: panelWidth,
    }
    setDragWidth(panelWidth)
  }

  const finishResize = useCallback((pointerId: number, cancelled = false) => {
    const drag = resizeRef.current
    if (!drag || drag.pointerId !== pointerId) return
    resizeRef.current = null
    if (resizeFrameRef.current !== null) window.cancelAnimationFrame(resizeFrameRef.current)
    resizeFrameRef.current = null
    pendingDragWidthRef.current = null
    setDragWidth(null)
    if (cancelled) return
    if (shouldCollapseInboxPanel(drag.latestRawWidth)) collapse()
    else setSavedWidth(drag.latestRawWidth)
  }, [collapse, setSavedWidth])

  useEffect(() => {
    if (!resizing) return
    const previousCursor = document.body.style.cursor
    const previousUserSelect = document.body.style.userSelect
    const moveResize = (event: PointerEvent) => {
      const drag = resizeRef.current
      if (!drag || drag.pointerId !== event.pointerId) return
      const rawWidth = drag.startWidth + event.clientX - drag.startX
      drag.latestRawWidth = rawWidth
      pendingDragWidthRef.current = clampInboxPanelWidth(rawWidth)
      if (resizeFrameRef.current !== null) return
      resizeFrameRef.current = window.requestAnimationFrame(() => {
        resizeFrameRef.current = null
        const next = pendingDragWidthRef.current
        pendingDragWidthRef.current = null
        if (next !== null) setDragWidth(next)
      })
    }
    const completeResize = (event: PointerEvent) => finishResize(event.pointerId)
    const cancelPointerResize = (event: PointerEvent) => finishResize(event.pointerId, true)
    const cancelResize = () => {
      const pointerId = resizeRef.current?.pointerId
      if (pointerId !== undefined) finishResize(pointerId, true)
    }

    document.body.style.cursor = 'col-resize'
    document.body.style.userSelect = 'none'
    window.addEventListener('pointermove', moveResize, true)
    window.addEventListener('pointerup', completeResize, true)
    window.addEventListener('pointercancel', cancelPointerResize, true)
    window.addEventListener('blur', cancelResize)
    return () => {
      document.body.style.cursor = previousCursor
      document.body.style.userSelect = previousUserSelect
      window.removeEventListener('pointermove', moveResize, true)
      window.removeEventListener('pointerup', completeResize, true)
      window.removeEventListener('pointercancel', cancelPointerResize, true)
      window.removeEventListener('blur', cancelResize)
    }
  }, [finishResize, resizing])

  const resizeWithKeyboard = (event: ReactKeyboardEvent<HTMLDivElement>) => {
    const step = event.shiftKey ? 64 : 24
    if (event.key === 'ArrowLeft') {
      event.preventDefault()
      if (panelWidth <= MIN_INBOX_PANEL_WIDTH) collapse()
      else setSavedWidth(panelWidth - step)
    } else if (event.key === 'ArrowRight') {
      event.preventDefault()
      setSavedWidth(panelWidth + step)
    } else if (event.key === 'Home') {
      event.preventDefault()
      collapse()
    } else if (event.key === 'End') {
      event.preventDefault()
      setSavedWidth(MAX_INBOX_PANEL_WIDTH)
    }
  }

  useImperativeHandle(ref, () => ({
    focus: () => composerRef.current?.focus(),
    expand,
    insertText: (text) => composerRef.current?.insertText(text),
  }))

  useEffect(() => {
    const onKeyDown = (event: KeyboardEvent) => {
      if ((event.metaKey || event.ctrlKey) && event.key === '\\') {
        event.preventDefault()
        if (collapsed) expand()
        else collapse()
      } else if (event.key === 'Escape' && !collapsed && window.innerWidth < 1400) {
        event.preventDefault()
        collapse()
      }
    }
    document.addEventListener('keydown', onKeyDown)
    return () => document.removeEventListener('keydown', onKeyDown)
  }, [collapse, collapsed, expand])

  const latestOutput = [...entries].reverse().find((entry) => entry.kind === 'activity' || (entry.kind === 'message' && entry.role === 'assistant'))?.id ?? null
  useEffect(() => {
    if (lastOutputRef.current && latestOutput && latestOutput !== lastOutputRef.current && collapsed) setHiddenOutput(true)
    lastOutputRef.current = latestOutput
  }, [collapsed, latestOutput])

  useEffect(() => {
    if (!pinnedRef.current || !scrollerRef.current) return
    scrollerRef.current.scrollTo({ top: scrollerRef.current.scrollHeight, behavior: streaming ? 'auto' : 'smooth' })
  }, [entries.length, streaming?.content, streaming?.status])

  const loadOlder = async () => {
    const scroller = scrollerRef.current
    const before = scroller?.scrollHeight ?? 0
    await conversation.fetchNextPage()
    requestAnimationFrame(() => {
      if (scroller) scroller.scrollTop += scroller.scrollHeight - before
    })
  }

  const submit = (markdown: string) => {
    const instruction = markdown.trim()
    if (!instruction || busy) return
    onSubmit(instruction, {
      focusKey: attached && active ? active.key : null,
      delegateModel: delegateModel || null,
      delegateTier: tier || null,
    })
    composerRef.current?.clear()
  }

  if (collapsed) {
    return (
      <aside className="relative z-20 flex h-full w-11 shrink-0 flex-col items-center border-r border-line bg-sidebar py-3" aria-label="Scout conversation collapsed">
        <button
          ref={expandButtonRef}
          type="button"
          onClick={expand}
          aria-label="Expand Scout conversation"
          aria-expanded={false}
          className="relative grid h-8 w-8 place-items-center rounded-md text-muted hover:bg-hover hover:text-fg"
        >
          <ChevronRight size={14} />
          {hiddenOutput && <span className="absolute right-0 top-0 h-1.5 w-1.5 rounded-full bg-accent" aria-label="New Scout output" />}
        </button>
        <div className="mt-5 grid h-8 w-8 place-items-center rounded-md border border-line text-muted" title="Scout">
          <Bot size={14} />
        </div>
        {(busy || conversation.data?.pages[0]?.working) && <span className="mt-2 h-1.5 w-1.5 animate-pulse rounded-full bg-success" aria-label="Scout is working" />}
        <MessageSquareText size={14} className="mt-auto text-ink-dim" />
      </aside>
    )
  }

  return (
    <>
      <button type="button" onClick={collapse} aria-label="Close Scout overlay" className="absolute inset-0 z-30 bg-black/45 min-[1400px]:hidden" />
      <aside
        className={cn(
          'absolute inset-y-0 left-0 z-40 flex shrink-0 flex-col border-r border-line bg-sidebar shadow-[var(--theme-shadow-3)] min-[1400px]:relative min-[1400px]:z-20 min-[1400px]:shadow-none',
          !resizing && 'motion-safe:transition-[width,transform] motion-safe:duration-200',
        )}
        style={{ width: `min(${panelWidth}px, calc(100% - 44px))` }}
        aria-label="Scout conversation"
      >
        <div
          role="separator"
          aria-label="Resize Scout conversation"
          aria-orientation="vertical"
          aria-valuemin={MIN_INBOX_PANEL_WIDTH}
          aria-valuemax={MAX_INBOX_PANEL_WIDTH}
          aria-valuenow={Math.round(panelWidth)}
          tabIndex={0}
          title="Drag to resize. Drag left past the minimum to collapse."
          onDoubleClick={() => setSavedWidth(DEFAULT_INBOX_PANEL_WIDTH)}
          onKeyDown={resizeWithKeyboard}
          onPointerDown={beginResize}
          className="group absolute -right-2 inset-y-0 z-50 flex w-4 touch-none cursor-col-resize items-center justify-center focus-visible:!outline-none"
        >
          <span
            className={cn(
              'grid h-12 w-3 place-items-center rounded-full border border-line-strong bg-raised text-ink-dim opacity-0 shadow-[var(--theme-shadow-2)] transition-[opacity,color,background-color] group-hover:opacity-100 group-focus:opacity-100 group-focus:text-fg',
              resizing && 'bg-accent text-surface opacity-100',
            )}
            aria-hidden
          >
            <GripVertical size={10} strokeWidth={1.75} />
          </span>
        </div>
        <header className="flex h-12 shrink-0 items-center gap-3 border-b border-line px-4">
          <span className="grid h-7 w-7 place-items-center rounded-md border border-line text-muted"><Bot size={14} /></span>
          <div className="min-w-0 flex-1">
            <div className="truncate font-sans text-[13px] font-medium text-fg">Scout</div>
            <div className="font-mono text-[9px] uppercase tracking-[0.07em] text-ink-dim">{focusMode ? 'Inbox conversation' : 'Assistant conversation'}</div>
          </div>
          <span className={cn('h-1.5 w-1.5 rounded-full', busy || conversation.data?.pages[0]?.working ? 'animate-pulse bg-success' : 'bg-line-strong')} aria-hidden />
          <button type="button" onClick={collapse} aria-label="Collapse Scout conversation" aria-expanded className="grid h-8 w-8 place-items-center rounded-md text-muted hover:bg-hover hover:text-fg">
            <ChevronLeft size={14} />
          </button>
        </header>

        <div
          ref={scrollerRef}
          onScroll={(event) => {
            const node = event.currentTarget
            pinnedRef.current = node.scrollHeight - node.scrollTop - node.clientHeight < 96
          }}
          className="min-h-0 flex-1 overflow-y-auto px-4 pb-6 pt-3"
          aria-live="polite"
        >
          {conversation.hasNextPage && (
            <div className="mb-5 flex justify-center">
              <Button size="sm" variant="ghost" onClick={() => void loadOlder()} disabled={conversation.isFetchingNextPage}>
                {conversation.isFetchingNextPage ? 'Loading' : 'Load earlier history'}
              </Button>
            </div>
          )}
          {conversation.isLoading ? (
            <div className="space-y-4 py-4"><Skeleton className="h-16 w-4/5 rounded-lg" /><Skeleton className="ml-auto h-12 w-3/5 rounded-lg" /><Skeleton className="h-24 w-full rounded-lg" /></div>
          ) : entries.length === 0 && !streaming ? (
            <div className="grid min-h-[320px] place-items-center text-center">
              <div className="max-w-xs">
                <span className="mx-auto grid h-10 w-10 place-items-center rounded-full border border-line text-muted"><Bot size={16} /></span>
                <h2 className="mt-4 font-sans text-base font-medium text-fg">{focusMode ? 'Work through Inbox with Scout' : 'Talk with Scout from anywhere'}</h2>
                <p className="mt-2 font-sans text-xs leading-5 text-muted">{focusMode ? 'The active decision is attached by default. Remove it to have a general, non-executing conversation.' : 'This conversation stays with you as you move through Talaria. General messages do not execute tools or mutations.'}</p>
              </div>
            </div>
          ) : (
            <div className="space-y-5">
              {entries.map((entry) => <TimelineEntry key={entry.id} entry={entry} onConfirm={onConfirm} onCancel={onCancel} onRetry={onRetry} onUndo={onUndo} />)}
              {streaming && (
                <>
                  <div className="ml-auto max-w-[86%] rounded-xl rounded-br-sm border border-line bg-raised px-3 py-2.5 font-sans text-[13px] leading-5 text-fg">
                    <Markdown>{streaming.user}</Markdown>
                  </div>
                  <div className="border-t border-line pt-4">
                    <div className="mb-2 flex items-center gap-2 font-mono text-[9px] uppercase tracking-[0.07em] text-ink-dim">
                      <span className="h-1.5 w-1.5 animate-pulse rounded-full bg-success" />{streaming.status}
                    </div>
                    {streaming.content && <div className="font-sans text-[13px] leading-5 text-fg"><Markdown>{streaming.content}</Markdown></div>}
                  </div>
                </>
              )}
            </div>
          )}
        </div>

        <div className="shrink-0 border-t border-line bg-sidebar/95 p-3 backdrop-blur">
          {notice && <div role="status" className="mb-2 rounded-md border border-line bg-panel px-3 py-2 font-sans text-[11px] leading-4 text-muted">{notice}</div>}
          {active && (
            <div className="mb-2 flex min-w-0 items-center gap-2 rounded-md border border-line bg-surface px-2.5 py-2">
              <Paperclip size={12} className={attached ? 'text-accent' : 'text-ink-dim'} />
              <button type="button" onClick={toggleActiveDecisionAttachment} className="min-w-0 flex-1 truncate text-left font-sans text-[11px] text-muted">
                {attached ? active.question : 'Decision detached — general conversation'}
              </button>
              <button type="button" onClick={toggleActiveDecisionAttachment} aria-label={attached ? 'Detach active decision' : 'Attach active decision'} className="grid h-6 w-6 place-items-center rounded text-ink-dim hover:bg-hover hover:text-fg">
                {attached ? <X size={12} /> : <Paperclip size={12} />}
              </button>
            </div>
          )}
          <div className="rounded-lg border border-line-strong bg-panel p-2 shadow-[var(--theme-shadow-2)]">
            <ChatComposer
              ref={composerRef}
              placeholder={attached ? 'Tell Scout what should happen…' : 'Message Scout…'}
              compactOnNarrow
              onSubmit={submit}
              onEscape={() => window.innerWidth < 1400 && collapse()}
              disabled={busy}
              rightControls={
                <div className="flex min-w-0 items-center gap-1.5">
                  <AgentChip agents={agents} value={delegateModel} onChange={(value) => { setDelegateModel(value); setTier('') }} />
                  <TierPicker tiers={selectedAgent?.tiers ?? []} value={tier} onChange={setTier} />
                </div>
              }
            />
          </div>
          <div className="mt-1.5 flex items-center justify-between gap-2 px-1 font-mono text-[8px] uppercase tracking-[0.06em] text-ink-dim">
            <span>{assistant?.configured ? `${assistant.name ?? 'Scout'} orchestrates` : 'Assistant not configured'}</span>
            <span>{agentsLoading ? 'Loading' : delegateModel ? 'Specialist ready' : attached ? 'Decision attached' : 'No tools'}</span>
          </div>
        </div>
      </aside>
    </>
  )
})

function TimelineEntry({
  entry,
  onConfirm,
  onCancel,
  onRetry,
  onUndo,
}: {
  entry: InboxTimelineEntry
  onConfirm: (entry: Extract<InboxTimelineEntry, { kind: 'activity' }>) => void
  onCancel: (entry: Extract<InboxTimelineEntry, { kind: 'activity' }>) => void
  onRetry: (entry: Extract<InboxTimelineEntry, { kind: 'activity' }>) => void
  onUndo: (entry: Extract<InboxTimelineEntry, { kind: 'activity' }>) => void
}) {
  if (entry.kind === 'context') {
    return (
      <div className="flex items-center gap-3 py-1">
        <span className="h-px flex-1 bg-line" />
        <a href={entry.focus.sourceHref} className="max-w-[72%] truncate font-mono text-[9px] uppercase tracking-[0.06em] text-ink-dim hover:text-muted">{entry.focus.question}</a>
        <span className="h-px flex-1 bg-line" />
      </div>
    )
  }
  if (entry.kind === 'message') {
    if (entry.role === 'user') {
      return <div className="ml-auto max-w-[86%] rounded-xl rounded-br-sm border border-line bg-raised px-3 py-2.5 font-sans text-[13px] leading-5 text-fg"><Markdown>{entry.content}</Markdown></div>
    }
    return (
      <div className="border-t border-line pt-4">
        {entry.delegateModel && <div className="mb-2 font-mono text-[9px] uppercase tracking-[0.07em] text-ink-dim">Consulted {entry.delegateModel}</div>}
        {entry.status === 'error'
          ? <p className="font-sans text-xs text-danger">Scout did not finish this response.</p>
          : <div className="font-sans text-[13px] leading-5 text-fg"><Markdown>{entry.content}</Markdown></div>}
      </div>
    )
  }

  const label = {
    proposal: 'Proposed action',
    confirmation: 'Confirmation required',
    completion: 'Completed',
    failure: 'Action failed',
    cancellation: 'Cancelled',
    undo: 'Undone',
  }[entry.activity]
  return (
    <section className={cn('rounded-lg border bg-panel p-3', entry.activity === 'failure' ? 'border-danger/45' : entry.activity === 'confirmation' ? 'border-accent/55' : 'border-line')} aria-label={label}>
      <div className="font-mono text-[9px] uppercase tracking-[0.07em] text-ink-dim">{label}</div>
      <h3 className="mt-1 font-sans text-[13px] font-medium text-fg">{entry.title}</h3>
      {entry.message && <p className="mt-1.5 font-sans text-[11px] leading-4 text-muted">{entry.message}</p>}
      {entry.activity === 'confirmation' && (
        <pre className="mt-3 max-h-40 overflow-auto whitespace-pre-wrap break-words rounded-md border border-line bg-surface p-2.5 font-mono text-[10px] leading-4 text-muted">{exactPreview(entry.details)}</pre>
      )}
      <div className="mt-3 flex flex-wrap items-center gap-2">
        {entry.activity === 'confirmation' && entry.confirmationToken && (
          <>
            <Button size="sm" onClick={() => onConfirm(entry)}>Confirm exact action</Button>
            <Button size="sm" variant="ghost" onClick={() => onCancel(entry)}>Cancel</Button>
          </>
        )}
        {entry.activity === 'failure' && entry.actionId && <Button size="sm" variant="outline" onClick={() => onRetry(entry)}>Retry</Button>}
        {entry.activity === 'completion' && entry.undoExpiresAt
          ? <Button size="sm" variant="ghost" onClick={() => onUndo(entry)}><RotateCcw size={12} /> Undo</Button>
          : entry.activity === 'completion' && <a href={entry.focus.sourceHref} className={buttonClasses({ variant: 'ghost', size: 'sm' })}><ExternalLink size={12} /> View result</a>}
        {(entry.activity === 'failure' || entry.activity === 'cancellation') && <a href={entry.focus.sourceHref} className={buttonClasses({ variant: 'ghost', size: 'sm' })}>Open source</a>}
      </div>
    </section>
  )
}

function exactPreview(value: unknown): string {
  if (typeof value === 'string') return value
  try {
    return JSON.stringify(value, null, 2)
  } catch {
    return String(value ?? '')
  }
}

// ui/src/components/inbox/InboxChatPanel.svelte
<script lang="ts">
  import { untrack } from 'svelte'
  import {
    Bot,
    ChevronLeft,
    ChevronRight,
    GripVertical,
    MessageSquareText,
    Paperclip,
    X,
  } from '@lucide/svelte'
  import { createQuery } from '@tanstack/svelte-query'
  import PendingAttachments from '@/components/chat/PendingAttachments.svelte'
  import ChatComposer from '@/components/chat/ChatComposer.svelte'
  import type { ChatComposerHandle } from '@/components/chat/chat-composer'
  import AssistantComposerControls from '@/components/inbox/AssistantComposerControls.svelte'
  import type { AssistantMode } from '@/components/inbox/assistant-composer-controls'
  import Button from '@/components/ui/Button.svelte'
  import Markdown from '@/components/ui/Markdown.svelte'
  import Skeleton from '@/components/ui/Skeleton.svelte'
  import { cn } from '@/lib/cn'
  import { fade, fly, slide, PANEL, QUICK } from '@/lib/motion'
  import { getJson } from '@/lib/fetch-json'
  import { useAgents } from '@/lib/agents'
  import { splitAttachments, uploadFile, type Attachment } from '@/lib/attachments'
  import { mergeInboxTimelinePages } from '@/lib/inbox-focus-timeline'
  import {
    DEFAULT_INBOX_PANEL_WIDTH,
    MAX_INBOX_PANEL_WIDTH,
    MIN_INBOX_PANEL_WIDTH,
    clampInboxPanelWidth,
    shouldCollapseInboxPanel,
  } from '@/lib/inbox-panel-size'
  import {
    useInboxFocusConversation,
    type FocusAssistant,
    type FocusItem,
    type InboxTimelineEntry,
  } from '@/lib/inbox-focus.svelte'
  import { useModels } from '@/lib/muse.svelte'
  import { useSkillLibrary } from '@/lib/workflows'
  import {
    PANEL_WIDTH_KEY,
    readPanelCollapsed,
    readPanelWidth,
    subscribePanelCollapsed,
    writePanelCollapsed,
    writePanelWidth,
    type InboxCommandOptions,
    type StreamingTurn,
  } from './inbox-chat-panel'
  import TimelineEntry from './TimelineEntry.svelte'

  interface AgentMcpSummary {
    id: string
    slug: string
    displayName: string
    servers: Array<{ name: string; extras: string[] }>
  }

  let {
    active,
    focusMode,
    assistant,
    busy,
    notice,
    streaming,
    onSubmit,
    onConfirm,
    onCancel,
    onRetry,
    onUndo,
  }: {
    active: FocusItem | null
    focusMode: boolean
    assistant: FocusAssistant | undefined
    busy: boolean
    notice: string | null
    streaming: StreamingTurn | null
    onSubmit: (instruction: string, options: InboxCommandOptions) => void
    onConfirm: (entry: Extract<InboxTimelineEntry, { kind: 'activity' }>) => void
    onCancel: (entry: Extract<InboxTimelineEntry, { kind: 'activity' }>) => void
    onRetry: (entry: Extract<InboxTimelineEntry, { kind: 'activity' }>) => void
    onUndo: (entry: Extract<InboxTimelineEntry, { kind: 'activity' }>) => void
  } = $props()

  // The owner named their assistant; use that name everywhere it appears. The
  // fallback is deliberately generic rather than a product name — an agent's
  // identity comes from its own persona, and hard-coding one here would put a
  // stranger's agent name in front of every customer.
  const assistantName = $derived(assistant?.name ?? 'your assistant')

  // Collapsed state persists in localStorage and stays in sync across this tab
  // (custom event) and other tabs (storage event) — the React version used
  // useSyncExternalStore; here a $state mirror updated by the subscription.
  let collapsed = $state(readPanelCollapsed())
  $effect(() => subscribePanelCollapsed(() => (collapsed = readPanelCollapsed())))
  const setCollapsed = (next: boolean) => writePanelCollapsed(next)

  // Saved width, likewise storage-synced. `committedWidth` mirrors the last
  // persisted value so drags that land on it can skip the write.
  let savedWidth = $state(DEFAULT_INBOX_PANEL_WIDTH)
  let committedWidth = DEFAULT_INBOX_PANEL_WIDTH
  $effect(() => {
    const syncWidth = () => {
      const next = readPanelWidth()
      committedWidth = next
      savedWidth = next
    }
    const syncStoredWidth = (event: StorageEvent) => {
      if (event.key === PANEL_WIDTH_KEY) syncWidth()
    }
    syncWidth()
    window.addEventListener('storage', syncStoredWidth)
    return () => window.removeEventListener('storage', syncStoredWidth)
  })
  function setSavedWidth(next: number) {
    const clamped = clampInboxPanelWidth(next)
    if (clamped === committedWidth) return
    committedWidth = clamped
    savedWidth = clamped
    writePanelWidth(clamped)
  }

  const conversation = useInboxFocusConversation()
  const agentsQuery = useAgents()
  const models = useModels()
  const skills = useSkillLibrary()
  const mcp = createQuery(() => ({
    queryKey: ['inbox-assistant-mcp'],
    // A failed read is not "this agent has no MCP servers". Swallowing it here
    // would make the tool picker quietly under-report what the agent can do,
    // with no way for anything downstream to tell that apart from a real empty
    // roster — `getJson` throws, so `mcp.isError` stays reachable.
    queryFn: (): Promise<{ agents: AgentMcpSummary[] }> => getJson<{ agents: AgentMcpSummary[] }>('/api/mcp'),
    staleTime: 30_000,
  }))
  let delegateModel = $state('')
  let responseModel = $state('')
  let mode = $state<AssistantMode>('normal')
  let attachments = $state<Attachment[]>([])
  let attachmentError = $state<string | null>(null)
  let detachedKey = $state<string | null>(null)
  let hiddenOutput = $state(false)
  let dragWidth = $state<number | null>(null)
  let composer = $state<ChatComposerHandle | null>(null)
  let expandButton = $state<HTMLButtonElement | null>(null)
  let scroller = $state<HTMLDivElement | null>(null)
  let pinned = true
  let lastOutput: string | null = null
  let resize: {
    pointerId: number
    startX: number
    startWidth: number
    latestRawWidth: number
  } | null = null
  let resizeFrame: number | null = null
  let pendingDragWidth: number | null = null
  const attached = $derived(Boolean(active && detachedKey !== active.key))
  function toggleActiveDecisionAttachment() {
    if (!active) return
    detachedKey = detachedKey === active.key ? null : active.key
  }
  const panelWidth = $derived(dragWidth ?? savedWidth)
  const resizing = $derived(dragWidth !== null)

  const entries = $derived(mergeInboxTimelinePages((conversation.data?.pages ?? []).map((page) => page.entries)))

  const agents = $derived([
    {
      id: '',
      label: assistant?.name ?? 'your assistant',
      role: assistant?.configured ? 'Personal orchestrator' : 'Not configured',
    },
    ...(agentsQuery.data?.agents ?? []).filter((agent) => agent.id !== assistant?.model),
  ])

  $effect(() => {
    const available = models.data?.models ?? []
    if (available.length === 0) {
      if (!models.isLoading) responseModel = ''
      return
    }
    if (available.some((model) => model.id === responseModel)) return
    const preferred = models.data?.effective
    responseModel = available.some((model) => model.id === preferred) ? preferred! : available[0]!.id
  })

  const effectiveAgentModel = $derived(delegateModel || assistant?.model || '')
  const skillOwner = $derived(skills.data?.find((owner) => owner.model === effectiveAgentModel))
  const skillItems = $derived.by(() => {
    const owners = skills.data ?? []
    const selected = owners.filter((owner) => owner.owner === 'shared' || owner.model === effectiveAgentModel)
    const seen = new Set<string>()
    return selected.flatMap((owner) => owner.skills.map((skill) => ({
      id: `${owner.owner}:${skill.name}`,
      label: skill.name,
      detail: owner.owner === 'shared' ? 'Shared' : owner.label,
    }))).filter((skill) => {
      if (seen.has(skill.label)) return false
      seen.add(skill.label)
      return true
    })
  })
  const mcpItems = $derived.by(() => {
    const roster = mcp.data?.agents ?? []
    const selected = roster.find((agent) => agent.slug === skillOwner?.owner)
      ?? roster.find((agent) => agent.displayName === (delegateModel
        ? agentsQuery.data?.agents.find((agent) => agent.id === delegateModel)?.label
        : assistant?.name))
    return (selected?.servers ?? []).map((server) => ({
      id: `${selected?.id ?? 'agent'}:${server.name}`,
      label: server.name,
      detail: server.extras.includes('built-in') ? 'Built in' : server.extras.includes('managed') ? 'Managed' : undefined,
    }))
  })

  function addAttachment(attachment: Attachment) {
    attachments = attachments.some((item) => item.id === attachment.id) ? attachments : [...attachments, attachment]
    attachmentError = null
  }

  async function uploadFiles(files: File[]) {
    attachmentError = null
    for (const file of files) {
      const result = await uploadFile(file)
      if ('error' in result) attachmentError = result.error
      else addAttachment(result)
    }
  }

  export function expand() {
    setCollapsed(false)
    hiddenOutput = false
    window.setTimeout(() => composer?.focus(), 0)
  }
  export function focus() {
    composer?.focus()
  }
  export function insertText(text: string) {
    composer?.insertText(text)
  }
  function collapse() {
    setCollapsed(true)
    window.setTimeout(() => expandButton?.focus(), 0)
  }

  function beginResize(event: PointerEvent) {
    if (event.button !== 0) return
    event.preventDefault()
    resize = {
      pointerId: event.pointerId,
      startX: event.clientX,
      startWidth: panelWidth,
      latestRawWidth: panelWidth,
    }
    dragWidth = panelWidth
  }

  function finishResize(pointerId: number, cancelled = false) {
    const drag = resize
    if (!drag || drag.pointerId !== pointerId) return
    resize = null
    if (resizeFrame !== null) window.cancelAnimationFrame(resizeFrame)
    resizeFrame = null
    pendingDragWidth = null
    dragWidth = null
    if (cancelled) return
    if (shouldCollapseInboxPanel(drag.latestRawWidth)) collapse()
    else setSavedWidth(drag.latestRawWidth)
  }

  $effect(() => {
    if (!resizing) return
    const previousCursor = document.body.style.cursor
    const previousUserSelect = document.body.style.userSelect
    const moveResize = (event: PointerEvent) => {
      const drag = resize
      if (!drag || drag.pointerId !== event.pointerId) return
      const rawWidth = drag.startWidth + event.clientX - drag.startX
      drag.latestRawWidth = rawWidth
      pendingDragWidth = clampInboxPanelWidth(rawWidth)
      if (resizeFrame !== null) return
      resizeFrame = window.requestAnimationFrame(() => {
        resizeFrame = null
        const next = pendingDragWidth
        pendingDragWidth = null
        if (next !== null) dragWidth = next
      })
    }
    const completeResize = (event: PointerEvent) => finishResize(event.pointerId)
    const cancelPointerResize = (event: PointerEvent) => finishResize(event.pointerId, true)
    const cancelResize = () => {
      const pointerId = resize?.pointerId
      if (pointerId !== undefined) finishResize(pointerId, true)
    }

    document.body.style.cursor = 'col-resize'
    document.body.style.userSelect = 'none'
    window.addEventListener('pointermove', moveResize, true)
    window.addEventListener('pointerup', completeResize, true)
    window.addEventListener('pointercancel', cancelPointerResize, true)
    window.addEventListener('blur', cancelResize)
    return () => {
      document.body.style.cursor = previousCursor
      document.body.style.userSelect = previousUserSelect
      window.removeEventListener('pointermove', moveResize, true)
      window.removeEventListener('pointerup', completeResize, true)
      window.removeEventListener('pointercancel', cancelPointerResize, true)
      window.removeEventListener('blur', cancelResize)
    }
  })

  function resizeWithKeyboard(event: KeyboardEvent) {
    const step = event.shiftKey ? 64 : 24
    if (event.key === 'ArrowLeft') {
      event.preventDefault()
      if (panelWidth <= MIN_INBOX_PANEL_WIDTH) collapse()
      else setSavedWidth(panelWidth - step)
    } else if (event.key === 'ArrowRight') {
      event.preventDefault()
      setSavedWidth(panelWidth + step)
    } else if (event.key === 'Home') {
      event.preventDefault()
      collapse()
    } else if (event.key === 'End') {
      event.preventDefault()
      setSavedWidth(MAX_INBOX_PANEL_WIDTH)
    }
  }

  function onGlobalKeyDown(event: KeyboardEvent) {
    if ((event.metaKey || event.ctrlKey) && event.key === '\\') {
      event.preventDefault()
      if (collapsed) expand()
      else collapse()
    } else if (event.key === 'Escape' && !collapsed && window.innerWidth < 1400) {
      event.preventDefault()
      collapse()
    }
  }

  const latestOutput = $derived(
    [...entries].reverse().find((entry) => entry.kind === 'activity' || (entry.kind === 'message' && entry.role === 'assistant'))?.id ?? null,
  )
  $effect(() => {
    if (lastOutput && latestOutput && latestOutput !== lastOutput && collapsed) hiddenOutput = true
    lastOutput = latestOutput
  })

  $effect(() => {
    // Deps mirror the React effect: entry count and the streaming turn's text.
    void entries.length
    void streaming?.content
    void streaming?.status
    const node = untrack(() => scroller)
    if (!pinned || !node) return
    node.scrollTo({ top: node.scrollHeight, behavior: streaming ? 'auto' : 'smooth' })
  })

  async function loadOlder() {
    const node = scroller
    const before = node?.scrollHeight ?? 0
    await conversation.fetchNextPage()
    requestAnimationFrame(() => {
      if (node) node.scrollTop += node.scrollHeight - before
    })
  }

  function submit(markdown: string) {
    const instruction = markdown.trim() || (attachments.length ? 'Review the attached context.' : '')
    if (!instruction || busy) return
    const split = splitAttachments(attachments)
    onSubmit(instruction, {
      focusKey: attached && active ? active.key : null,
      delegateModel: delegateModel || null,
      responseModel: responseModel || null,
      mode,
      attachmentIds: split.attachmentIds,
      refs: split.refs,
    })
    composer?.clear()
    attachments = []
  }
</script>

<svelte:document onkeydown={onGlobalKeyDown} />

{#if collapsed}
  <aside class="relative z-20 flex h-full w-11 shrink-0 flex-col items-center border-r border-line bg-sidebar py-3" aria-label="Assistant conversation collapsed">
    <button
      bind:this={expandButton}
      type="button"
      onclick={expand}
      aria-label="Expand assistant conversation"
      aria-expanded={false}
      class="relative grid h-8 w-8 place-items-center rounded-md text-muted hover:bg-hover hover:text-fg"
    >
      <ChevronRight size={14} />
      {#if hiddenOutput}<span class="absolute right-0 top-0 h-1.5 w-1.5 rounded-full bg-accent" aria-label="New assistant output"></span>{/if}
    </button>
    <div class="mt-5 grid h-8 w-8 place-items-center rounded-md border border-line text-muted" title={assistantName}>
      <Bot size={14} />
    </div>
    {#if busy || conversation.data?.pages[0]?.working}<span class="mt-2 h-1.5 w-1.5 animate-pulse rounded-full bg-success" aria-label="Assistant is working"></span>{/if}
    <MessageSquareText size={14} class="mt-auto text-ink-dim" />
  </aside>
{:else}
  <button type="button" onclick={collapse} aria-label="Close assistant overlay" class="absolute inset-0 z-30 bg-black/45 min-[1400px]:hidden"></button>
  <aside
    class={cn(
      'absolute inset-y-0 left-0 z-40 flex shrink-0 flex-col border-r border-line bg-sidebar shadow-[var(--theme-shadow-3)] min-[1400px]:relative min-[1400px]:z-20 min-[1400px]:shadow-none',
      !resizing && 'motion-safe:transition-[width,transform] motion-safe:duration-200',
    )}
    style:width="min({panelWidth}px, calc(100% - 44px))"
    aria-label="Assistant conversation"
  >
    <div
      role="separator"
      aria-label="Resize assistant conversation"
      aria-orientation="vertical"
      aria-valuemin={MIN_INBOX_PANEL_WIDTH}
      aria-valuemax={MAX_INBOX_PANEL_WIDTH}
      aria-valuenow={Math.round(panelWidth)}
      tabindex="0"
      title="Drag to resize. Drag left past the minimum to collapse."
      ondblclick={() => setSavedWidth(DEFAULT_INBOX_PANEL_WIDTH)}
      onkeydown={resizeWithKeyboard}
      onpointerdown={beginResize}
      class="group absolute -right-2 inset-y-0 z-50 flex w-4 touch-none cursor-col-resize items-center justify-center focus-visible:!outline-none"
    >
      <span
        class={cn(
          'grid h-12 w-3 place-items-center rounded-full border border-line-strong bg-raised text-ink-dim opacity-0 shadow-[var(--theme-shadow-2)] transition-[opacity,color,background-color] group-hover:opacity-100 group-focus:opacity-100 group-focus:text-fg',
          resizing && 'bg-accent text-surface opacity-100',
        )}
        aria-hidden="true"
      >
        <GripVertical size={10} strokeWidth={1.75} />
      </span>
    </div>
    <header class="flex h-12 shrink-0 items-center gap-3 border-b border-line px-4">
      <span class="grid h-7 w-7 place-items-center rounded-md border border-line text-muted"><Bot size={14} /></span>
      <div class="min-w-0 flex-1">
        <div class="truncate font-sans text-[13px] font-medium text-fg">{assistantName}</div>
        <div class="font-mono text-[9px] uppercase tracking-[0.07em] text-ink-dim">{focusMode ? 'Inbox conversation' : 'Assistant conversation'}</div>
      </div>
      <span class={cn('h-1.5 w-1.5 rounded-full', busy || conversation.data?.pages[0]?.working ? 'animate-pulse bg-success' : 'bg-line-strong')} aria-hidden="true"></span>
      <button type="button" onclick={collapse} aria-label="Collapse assistant conversation" aria-expanded={true} class="grid h-8 w-8 place-items-center rounded-md text-muted hover:bg-hover hover:text-fg">
        <ChevronLeft size={14} />
      </button>
    </header>

    <div
      bind:this={scroller}
      onscroll={(event) => {
        const node = event.currentTarget
        pinned = node.scrollHeight - node.scrollTop - node.clientHeight < 96
      }}
      class="min-h-0 flex-1 overflow-y-auto px-4 pb-6 pt-3"
      aria-live="polite"
    >
      {#if conversation.hasNextPage}
        <div class="mb-5 flex justify-center">
          <Button size="sm" variant="ghost" onclick={() => void loadOlder()} disabled={conversation.isFetchingNextPage}>
            {conversation.isFetchingNextPage ? 'Loading' : 'Load earlier history'}
          </Button>
        </div>
      {/if}
      {#if conversation.isLoading}
        <div class="space-y-4 py-4"><Skeleton class="h-16 w-4/5 rounded-lg" /><Skeleton class="ml-auto h-12 w-3/5 rounded-lg" /><Skeleton class="h-24 w-full rounded-lg" /></div>
      {:else if entries.length === 0 && !streaming}
        <div class="grid min-h-[320px] place-items-center text-center">
          <div class="max-w-xs">
            <span class="mx-auto grid h-10 w-10 place-items-center rounded-full border border-line text-muted"><Bot size={16} /></span>
            <h2 class="mt-4 font-sans text-base font-medium text-fg">{focusMode ? `Work through Inbox with ${assistantName}` : `Talk with ${assistantName} from anywhere`}</h2>
            <p class="mt-2 font-sans text-xs leading-5 text-muted">{focusMode ? 'The active decision is attached by default. Remove it to have a general, non-executing conversation.' : 'This conversation stays with you as you move through Talaria. General messages do not execute tools or mutations.'}</p>
          </div>
        </div>
      {:else}
        <div class="space-y-5">
          {#each entries as entry (entry.id)}
            <div in:fade={{ duration: 150 }} out:fade={QUICK}>
              <TimelineEntry
                {entry}
                readOnly={!focusMode}
                {onConfirm}
                {onCancel}
                {onRetry}
                {onUndo}
              />
            </div>
          {/each}
          {#if streaming}
            <div class="ml-auto max-w-[86%] rounded-xl rounded-br-sm border border-line bg-raised px-3 py-2.5 font-sans text-[13px] leading-5 text-fg">
              <Markdown children={streaming.user} />
            </div>
            <div class="border-t border-line pt-4">
              <div class="mb-2 flex items-center gap-2 font-mono text-[9px] uppercase tracking-[0.07em] text-ink-dim">
                <span class="h-1.5 w-1.5 animate-pulse rounded-full bg-success"></span>{streaming.status}
              </div>
              {#if streaming.content}<div class="font-sans text-[13px] leading-5 text-fg"><Markdown children={streaming.content} /></div>{/if}
            </div>
          {/if}
        </div>
      {/if}
    </div>

    <div class="shrink-0 border-t border-line bg-sidebar/95 p-2 backdrop-blur">
      {#if notice}<div role="status" transition:slide={{ duration: 150 }} class="mb-2 rounded-md border border-line bg-panel px-3 py-2 font-sans text-[11px] leading-4 text-muted">{notice}</div>{/if}
      {#if attachmentError}<div role="alert" transition:slide={{ duration: 150 }} class="mb-2 rounded-md border border-danger/45 bg-panel px-3 py-2 font-sans text-[11px] leading-4 text-danger">{attachmentError}</div>{/if}
      {#if active}
        <div in:fly={PANEL} out:fade={QUICK} class="mb-2 flex min-w-0 items-center gap-2 rounded-md border border-line bg-surface px-2.5 py-2">
          <Paperclip size={12} class={attached ? 'text-accent' : 'text-ink-dim'} />
          <button type="button" onclick={toggleActiveDecisionAttachment} class="min-w-0 flex-1 truncate text-left font-sans text-[11px] text-muted">
            {attached ? active.question : 'Decision detached — general conversation'}
          </button>
          <button type="button" onclick={toggleActiveDecisionAttachment} aria-label={attached ? 'Detach active decision' : 'Attach active decision'} class="grid h-6 w-6 place-items-center rounded text-ink-dim hover:bg-hover hover:text-fg">
            {#if attached}<X size={12} />{:else}<Paperclip size={12} />{/if}
          </button>
        </div>
      {/if}
      <div class="flex flex-col gap-2 rounded-lg border border-line-strong bg-panel p-2 shadow-[var(--theme-shadow-2)]">
        <PendingAttachments items={attachments} onRemove={(id) => (attachments = attachments.filter((item) => item.id !== id))} />
        <ChatComposer
          bind:this={composer}
          placeholder={attached ? `Tell ${assistantName} what should happen…` : `Message ${assistantName}…`}
          onSubmit={submit}
          onFiles={(files) => void uploadFiles(files)}
          onEscape={() => window.innerWidth < 1400 && collapse()}
          disabled={busy}
          canSend={attachments.length > 0 || undefined}
        >
          {#snippet controlRail()}
            <AssistantComposerControls
              {agents}
              agentValue={delegateModel}
              onAgentChange={(value) => (delegateModel = value)}
              models={models.data?.models ?? []}
              modelValue={responseModel}
              onModelChange={(value) => (responseModel = value)}
              modelsLoading={models.isLoading}
              {mode}
              onModeChange={(next) => (mode = next)}
              {mcpItems}
              {skillItems}
              onAttach={addAttachment}
              onTranscript={(text) => composer?.insertText(text)}
              disabled={busy}
            />
          {/snippet}
        </ChatComposer>
      </div>
      <div class="mt-1.5 flex items-center justify-between gap-2 px-1 font-mono text-[8px] uppercase tracking-[0.06em] text-ink-dim">
        <span>{assistant?.configured ? `${assistant.name ?? 'your assistant'} orchestrates` : 'Assistant not configured'}</span>
        <span>{agentsQuery.isLoading ? 'Loading' : delegateModel ? 'Specialist ready' : attached ? 'Decision attached' : 'No tools'}</span>
      </div>
    </div>
  </aside>
{/if}
