// ui/src/components/assistant/SkillEditor.svelte
<script lang="ts">
  import { createQuery } from '@tanstack/svelte-query'
  import { Trash2 } from '@lucide/svelte'
  import { confirm } from '@/components/ui/confirm.svelte'
  import Button from '@/components/ui/Button.svelte'
  import Modal from '@/components/ui/Modal.svelte'
  import QueryError from '@/components/ui/QueryError.svelte'
  import SkeletonRows from '@/components/ui/SkeletonRows.svelte'
  import InternalEditorModal from '@/components/fleet/InternalEditorModal.svelte'
  import { getJson } from '@/lib/fetch-json'
  import { type Assistant } from '@/lib/assistant'

  // The full workspace editor (history + diff + restore) for one owned skill.
  let {
    assistant,
    name,
    onClose,
    onChanged,
  }: {
    assistant: Assistant
    name: string
    onClose: () => void
    onChanged: () => void
  } = $props()

  let busy = $state(false)
  // This used to hand back whatever the body was, status ignored: a 500 whose
  // body is `{ error }` became `{ content: undefined }` and a non-JSON body
  // became `{ content: '' }` — either way the editor mounted EMPTY, and the
  // first Ctrl+S wrote that emptiness over the real SKILL.md.
  const query = createQuery(() => ({
    queryKey: ['assistant-skill', assistant.slug, name],
    queryFn: (): Promise<{ content: string }> => getJson<{ content: string }>(`/api/skills/${assistant.slug}/${name}`),
  }))

  const save = async (md: string) => {
    busy = true
    try {
      await fetch(`/api/skills/${assistant.slug}/${name}`, {
        method: 'PUT',
        credentials: 'same-origin',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ content: md }),
      })
      onChanged()
    } finally {
      busy = false
    }
  }

  const remove = async () => {
    if (!(await confirm({ title: 'Remove skill', message: `Remove the "${name}" skill?`, confirmLabel: 'Remove', danger: true }))) return
    await fetch(`/api/skills/${assistant.slug}/${name}`, { method: 'DELETE', credentials: 'same-origin' })
    onChanged()
    onClose()
  }
</script>

<!-- The editor seeds once from `value`, so it can't mount before the content
     arrives — but the click must land NOW: show the same modal shell with a
     prose-bar body, then swap in the real editor. -->
{#if query.data === undefined}
  <Modal open {onClose} title={`${name} · SKILL.md`} width="max-w-6xl">
    <div class="h-[76vh] pt-2">
      {#if query.isError}
        <QueryError error={query.error} title={`Could not open ${name}`} onRetry={() => void query.refetch()} />
      {:else}
        <SkeletonRows rows={8} />
      {/if}
    </div>
  </Modal>
{:else}
  <InternalEditorModal
    open
    {onClose}
    title={`${name} · SKILL.md`}
    subtitle="A playbook your assistant follows. Edits are live on its next run."
    value={query.data.content}
    editable
    saving={busy}
    onSave={save}
    history={{ kind: 'skill', owner: assistant.slug, name }}
    muse={{ kind: 'skill', context: `A skill for ${assistant.displayName}, a personal AI assistant.` }}
  >
    {#snippet footerExtra()}
      <Button variant="ghost" size="sm" onclick={() => void remove()}>
        <Trash2 size={14} class="mr-1.5" /> Delete skill
      </Button>
    {/snippet}
  </InternalEditorModal>
{/if}

// ui/src/components/workflows/skill-editor.tsx
// The Studio's skill editor — one SKILL.md in the full workspace editor
// (rich + Muse drafting + version history). Same contract as the agent-view
// editor: reads live, Hermes picks up saves on the agent's next run.
import { useState } from 'react'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { Button } from '@/components/ui/button'
import { Skeleton } from '@/components/ui/skeleton'
import { confirm } from '@/components/ui/confirm'
import { QueryError } from '@/components/ui/query-state'
import { getJson } from '@/lib/fetch-json'
import { InternalEditorModal } from '@/components/fleet/internal-editor-modal'

export function StudioSkillEditor({
  owner,
  ownerLabel,
  name,
  canEdit,
  onClose,
}: {
  owner: string
  ownerLabel: string
  name: string
  canEdit: boolean
  onClose: () => void
}) {
  const qc = useQueryClient()
  // 404 is NOT forgiven into a null here: the editor is opened from a library
  // row, so "no such skill" is a real failure worth naming — and the route
  // sends its reason as `{ error }`, which `readJson` lifts into the message.
  const query = useQuery({
    queryKey: ['skill', owner, name],
    queryFn: (): Promise<{ content: string; files: string[] }> => getJson<{ content: string; files: string[] }>(`/api/skills/${owner}/${name}`),
  })
  const { data } = query
  const [busy, setBusy] = useState(false)

  const save = async (content: string) => {
    setBusy(true)
    try {
      await fetch(`/api/skills/${owner}/${name}`, {
        method: 'PUT',
        credentials: 'same-origin',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ content }),
      })
      await qc.invalidateQueries({ queryKey: ['skill-library'] })
      await qc.invalidateQueries({ queryKey: ['skills'] })
      await qc.invalidateQueries({ queryKey: ['skill', owner, name] })
    } finally {
      setBusy(false)
    }
  }
  const remove = async () => {
    if (!(await confirm({ title: 'Delete skill', message: `Delete "${name}"? Workflows bound to it will flag it as missing.`, confirmLabel: 'Delete', danger: true }))) return
    await fetch(`/api/skills/${owner}/${name}`, { method: 'DELETE', credentials: 'same-origin' })
    await qc.invalidateQueries({ queryKey: ['skill-library'] })
    await qc.invalidateQueries({ queryKey: ['skills'] })
    onClose()
  }

  // The editor seeds ONCE from `value` — don't mount it until content is here.
  // A failed read must never seed it with '': saving from there would replace
  // the real SKILL.md with an empty file.
  if (!data)
    return (
      <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40" onClick={query.isError ? onClose : undefined}>
        <div className="w-full max-w-3xl space-y-3 rounded-2xl bg-[var(--theme-panel)] p-6" onClick={(e) => e.stopPropagation()}>
          {query.isError ? (
            <QueryError
              variant="compact"
              error={query.error}
              title={`Could not open ${name}`}
              onRetry={() => void query.refetch()}
            />
          ) : (
            <>
              <Skeleton className="h-2.5 w-2/3 rounded-full" />
              <Skeleton className="h-2.5 w-full rounded-full" delay={0.12} />
              <Skeleton className="h-2.5 w-3/4 rounded-full" delay={0.24} />
            </>
          )}
        </div>
      </div>
    )

  return (
    <InternalEditorModal
      open
      onClose={onClose}
      title={`${name} · SKILL.md`}
      subtitle={`${ownerLabel} — read live; agents pick up edits on their next run.`}
      value={data.content}
      editable={canEdit}
      saving={busy}
      onSave={save}
      history={{ kind: 'skill', owner, name }}
      muse={{
        kind: 'skill',
        context:
          owner === 'shared'
            ? 'A shared skill available to every agent in the fleet. SKILL.md format: a heading, a "When to use" line, then concrete numbered steps.'
            : `A skill for the "${ownerLabel}" agent. SKILL.md format: a heading, a "When to use" line, then concrete numbered steps.`,
      }}
      footerExtra={
        canEdit ? (
          <Button variant="ghost" size="sm" onClick={() => void remove()}>
            Delete skill
          </Button>
        ) : undefined
      }
    />
  )
}
